- docs/reference/pf-command-reference.md
- src/promptflow/promptflow/_cli/_pf/_flow.py
- src/promptflow/promptflow/_sdk/operations/_flow_operations.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_local_operations.py
Use a private SDK interface `pf_client.flows._generate_tools_meta` instead of `pf flow validate` with private parameters for vs code extension to generate tools meta.
> feat: private interface for vs extension to generate tools meta

- src/promptflow/promptflow/executor/_errors.py
- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/e2etests/test_executor_happypath.py
- src/promptflow/tests/executor/unittests/executor/test_flow_executor.py
- src/promptflow/tests/test_configs/flows/default_input/flow.dag.yaml
- src/promptflow/tests/test_configs/flows/default_input/test_print_aggregation.py
- src/promptflow/tests/test_configs/flows/default_input/test_print_input.py
- Honor flow input's default value in yaml for single node/flow/bulk run.
- For bulk run, default value should be in higher priority than default mapping. Since default value is directly assigned by customer. So, don't assign default mapping when there is default value.
> [Executor][Internal]Apply default input value in flow executor

- src/promptflow/promptflow/azure/operations/_flow_opearations.py
- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_run_operations.py
Fix a bug that traverse_directory hasn't been imported correctly
> fix: traverse directory import

- src/promptflow/promptflow/_utils/exception_utils.py
- src/promptflow/promptflow/_utils/utils.py
- src/promptflow/tests/executor/unittests/_utils/test_exception_utils.py
Use user agent as `componentName` field in `ErrorResponse`
> Use user agent as componentName in ErrorResponse

- src/promptflow/promptflow/executor/_line_execution_process_pool.py
Move import to the head of the file to avoid package references.
> [PromptFlow] Move import to the head of the file to avoid package references.

- examples/flows/chat/chat-with-wikipedia/get_wiki_url.py
- examples/flows/standard/basic/hello.py
- examples/flows/standard/web-classification/convert_to_dict.py
> fix a few typo identify by GPT

- src/promptflow/promptflow/_sdk/operations/_run_operations.py
- src/promptflow/promptflow/contracts/_run_management.py
- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_run_operations.py
Include `create_time` in contract with visualize.
> [promptflow][SDK/CLI] Add create_time in contract with visualize

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/executor/_errors.py
- src/promptflow/promptflow/executor/flow_validator.py
- src/promptflow/tests/executor/e2etests/test_executor_validation.py
- src/promptflow/tests/executor/unittests/executor/test_flow_validator.py
- src/promptflow/tests/test_configs/flows/flow_with_list_input/flow.dag.yaml
- src/promptflow/tests/test_configs/flows/flow_with_list_input/print_val.py
This is for bugfixing :
when user input List or Object, we use load user input as Json string and parse it as json first.  If the json string is not valid, then error would raised. We used to raise InputTypeError, but this definitely not illustrate the essence. So we try catch this specific exception for special handling.
> Handle JSONDecodeError exception when executor is resolving the inputs type convert

- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/promptflow/executor/flow_validator.py
- src/promptflow/tests/executor/unittests/executor/test_flow_executor.py
- src/promptflow/tests/executor/unittests/executor/test_flow_validator.py
Improve error message for aggregation input's validation.
And move these validation code to flow_validator.py
All of these errors are system error.
> Improve error message for aggregation input's validation.

- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/_utils.py
- src/promptflow/promptflow/_sdk/entities/_connection.py
- src/promptflow/promptflow/_sdk/schemas/_connection.py
- src/promptflow/tests/conftest.py
- src/promptflow/tests/executor/unittests/_core/test_tools_manager.py
- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_cli_with_azure.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_custom_strong_type_connection.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_run.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_test.py
- src/promptflow/tests/sdk_cli_test/unittests/test_utils.py
- src/promptflow/tests/test_configs/connections/custom_strong_type_connection.yaml
- src/promptflow/tests/test_configs/connections/update_custom_strong_type_connection.yaml
- src/promptflow/tests/test_configs/flows/custom_strong_type_connection_basic_flow/flow.dag.yaml
- src/promptflow/tests/test_configs/flows/custom_strong_type_connection_basic_flow/requirements.txt
This PR does the following things:
1. Enable test for custom strong type connection, including connection CRUD, basic flow test&run.
2. Store package and package version of the connection module in order for the local vs code extension to show package info for each created connection.
3. Support user script to use their custom connection configs like **connection.key**
4. Provide refresh_connections_dir in order for the vs code extension to generate and refresh the connections directory, so that ui can show the supported types in current env
> Store package and package version for custom strong type connection, add test and support connection.key

- scripts/tool/utils/tool_utils.py
- src/promptflow/promptflow/contracts/tool.py
Support generate tool meta yaml for custom package tool with custom strong type connection.
Tool yaml is used to generate flow.tools.json for package tools. And both portal and local uses the meta in flow.tools.json to display the node interface. For portal, the node input type should be CustomConnection. While for local extension, the node input type should display as custom strong type connection. So we add a another field "custom_type" for local extension to display (if no custom_type found, read "type" field), and portal would still read the "type" field.
Test cases:
1. Tool uses custom strong type connection:
tool:
```python
from promptflow import ToolProvider, tool
from my_tool_package.connections import MyFirstConnection
class MyTool(ToolProvider):
"""
Doc reference :
"""
def …
```
> Support gen tool meta for package tool with custom strong type connection

- src/promptflow/promptflow/_core/_errors.py
- src/promptflow/promptflow/_core/tools_manager.py
- src/promptflow/promptflow/_utils/exception_utils.py
- src/promptflow/promptflow/executor/_errors.py
- src/promptflow/promptflow/executor/_tool_resolver.py
- src/promptflow/tests/executor/e2etests/test_executor_happypath.py
- src/promptflow/tests/executor/e2etests/test_executor_validation.py
- src/promptflow/tests/executor/e2etests/test_package_tool.py
- src/promptflow/tests/executor/package_tools/tool_with_init_error.py
- src/promptflow/tests/executor/package_tools/tool_with_init_error/flow.dag.yaml
- src/promptflow/tests/executor/package_tools/tool_with_init_error/package_tool_definition.json
- src/promptflow/tests/executor/unittests/_utils/test_exception_utils.py
- src/promptflow/tests/executor/unittests/executor/test_errors.py
- src/promptflow/tests/executor/unittests/executor/test_exceptions.py
- src/promptflow/tests/executor/unittests/executor/test_tool_resolver.py
Currently, for loading tool error, the error message does not contain the name of the node where the error occurred, which makes it difficult for users to locate the problematic nod. So we need to improve the error handling here.
Changes in this PR:
1. Define an error type: ToolLoadError, to encapsulate load errors thrown from a third-party tool package. Its most important function is to record the error target and module.
2. Define an error type: ResolveToolError, to append the name of the failed node to the error message, which can help user locate the error more quickly. ResolveToolError is a typeless error, so we need to rely on inner_error to redefine its additional_info and error_codes.
3. To achieve the second point, we improved the handling of error_codes in ExceptionPresenter.
4. …
> [Feature] Improve error handling for loading tool error.

- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/e2etests/test_executor_happypath.py
In bulk run, if validate_input enabled, the input would be converted based on flow input type. We need to update run info as well to make sure the UI would correctly populate right-typed value
> Update Run Info Inputs once input resolved in bulk run

- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/unittests/executor/test_flow_executor.py
Add warning when no column mapping provided.
> Add warning when no column mapping provided.

- .github/workflows/promptflow-release-testing-matrix.yml
3.12 is too pre-release, some tools like pytest-mock doesn't support pre-release version of python.
> Fix testing matrix to remove python 3 12

- src/promptflow/promptflow/exceptions.py
- src/promptflow/tests/executor/unittests/executor/test_exceptions.py
If we set parameter does not align with `message_format`, show <Param> to customer. For now, we will throw KeyError, which is one bad experience for customer.
For example:
```
ex = PromptflowException(
message_format="Test exception message with parameters: {param}, {param1}.",
param="test_param",
)
```
Will raise KeyError for ex.message, since we don't have `param1`.
After this PR, ex.message = "Test exception message with parameters: test_param, <param>."
> Make error message format more robust.

- .github/workflows/promptflow-executor-e2e-test.yml
Langchain changed numexpr as optional package in https://github.com/langchain-ai/langchain/pull/11049.
So, `pip install langchain` will not install `numexpr`.
Add `pip install numexpr` to fix e2e test because we need call `langchain.agents.load_tools.load_tools`.
Test failed because can't apply this branch's yaml to install numexpr.
Trigger e2e test separately and test succeeded.
https://github.com/microsoft/promptflow/actions/runs/6440435201
> numexpr is one optional package for langchain, install it for e2e test.

- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/promptflow/executor/flow_validator.py
- src/promptflow/tests/executor/unittests/executor/test_flow_validator.py
Resolve type for exec_aggreation's flow inputs.
**Before:**
Aggregation node's flow input is a list of strings.
(Didn't honor the definition in yaml file)
For example: the below flow input will be string "123", but not int 123 when default value is used.
**After:**
Aggregation node's flow input is a list of objects, whose type is specified in yaml file.
Extract `_convert_input_by_type` to convert each item, then we could reuse the error message.
> Resolve input type for exec_aggreation.

- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/_utils.py
- src/promptflow/tests/conftest.py
- src/promptflow/tests/executor/unittests/_core/test_tools_manager.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_custom_strong_type_connection.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_run.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_test.py
- src/promptflow/tests/sdk_cli_test/unittests/test_utils.py
This pull request does the following two things:
1. Bugfix. Add lock to prevent concurrency issue when refreshing connections dir.
2. Enable custom strong type connection tests that need custom tool package.
> Add lock to prevent concurrency issue when refreshing connections dir and enable custom strong type connection tests

- src/promptflow-tools/promptflow/version.txt
- src/promptflow-tools/requirements.txt
remove pinned version of promptflow due to last hotfix and upgrade pf-tool version
> remove pf version pinning and upgrade pf-tools to 0.1.0b8

- src/promptflow/promptflow/_utils/utils.py
- src/promptflow/promptflow/executor/_line_execution_process_pool.py
The `start_time` in `_timeout_process_wrapper` is the start time for a line, not for the whole batch run, so we should use actual start time to calculate execution time.
> [Bugfix][Executor] Use actual start time to calculate execution time

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_core/tool_meta_generator.py
- src/promptflow/tests/test_configs/flows/script_with___file__/script_with___file__.py
Set encoding as `utf-8` as reading meta file.
For windows, the default encoding is `cp1252`. Use `utf-8` since that's more common.
And could read file with "Private Use" Unicode character.
> Read tool file by utf-8 encoding.

- src/promptflow/promptflow/executor/_tool_resolver.py
- src/promptflow/tests/executor/unittests/_utils/test_generate_tool_meta_utils.py
- src/promptflow/tests/executor/unittests/executor/test_tool_resolver.py
- src/promptflow/tests/test_configs/flows/script_with___file__/script_with___file__.py
- src/promptflow/tests/test_configs/flows/script_with_special_character/script_with_special_character.meta.json
- src/promptflow/tests/test_configs/flows/script_with_special_character/script_with_special_character.py
For LLM/Prompt/CUSTOM_LLM tool, we need to read file to resolve the tool.
If there is special character, will introduce unexpected error.
So, we set encoding as "uts-8".
This is continuing PR for https://github.com/microsoft/promptflow/pull/759
> Fix reading special character issue for tool resolver

- src/promptflow-tools/promptflow/tools/common.py
- src/promptflow-tools/tests/test_common.py
Issue:
Root cause:
Caused by inappropriate regrex expr to match role in prompt. It is unexpected to match role word if it is in content string. For example, should not identify `function` as a role for input `"system:\nthis is my function:\ndef hello"`
Solution:
Fixed by modifying the regrex expr and added more tests of parsing logic.
> fix parsing role in prompt issue

- src/promptflow-tools/promptflow/tools/common.py
- src/promptflow-tools/tests/test_common.py
add new separator for role parsing logic in chat string
- for system/user/assistant/function role, support single # prefix;
- for function's name/content role, support double # prefix
> add new separator for role parsing logic

- src/promptflow/promptflow/executor/flow_executor.py
[PR](https://github.com/microsoft/promptflow/pull/651/files) changed link path, so the error message is not valid.
Replace link by aka link.
Then we only need to update redirection rule after changing link
> Fix error message's link for column mapping usage

- src/promptflow/promptflow/_utils/multimedia_utils.py
`dict` subscribing is not supported in py38. This PR fixed it with `typing.Dict`
> [SDK]Fix dict subscribing in py38

- docs/cloud/azureai/quick-start.md
- examples/flows/standard/basic-with-connection/README.md
- examples/flows/standard/basic/README.md
- examples/flows/standard/flow-with-additional-includes/README.md
- examples/flows/standard/flow-with-symlinks/README.md
- examples/flows/standard/web-classification/README.md
> [Samples]update compute to fix failed samples CI

- src/promptflow/promptflow/executor/flow_executor.py
> Remove working_dir

- src/promptflow/promptflow/_utils/connection_utils.py
- src/promptflow/tests/executor/unittests/_core/test_tools_manager.py
- src/promptflow/tests/executor/unittests/_utils/test_connection_utils.py
Fix the comments patten from "String, The api key." to "String type. The api key." when generate connection template.
Fixed yaml example:
```yaml
$schema: https://azuremlschemas.azureedge.net/promptflow/latest/CustomStrongTypeConnection.schema.json
name: "to_replace_with_connection_name"
type: custom
custom_type: MyCustomConnectionMissingTypeComments
module: executor.unittests._utils.test_connection_utils
package: test-package
package_version: 0.0.1
configs:
api_base: "to_replace_with_api_base"  #  String type.
secrets:      # must-have
api_key: "to_replace_with_api_key"  #  String type. The api key.
```
> Fix comments when generate connection template

- src/promptflow/promptflow/_utils/multimedia_utils.py
- src/promptflow/promptflow/contracts/multimedia.py
- src/promptflow/tests/executor/unittests/_utils/test_multimedia_utils.py
> Add UT for multimedia_utils

- examples/tools/tool-package-quickstart/my_tool_package/tools/tool_with_custom_strong_type_connection.py
Fix typo in tools example quickstart. The api-key in custom strong type connection tool should be secret type.
> Fix typo in tools example quickstart

- src/promptflow/tests/sdk_cli_test/e2etests/test_orm.py
We found that in some (edge) cases, the `created_on` timestamp can be same in SDK ORM end-to-end test, and this will break existing assert logic; so we update the compare logic from `>` to `>=` in this PR.
> [promptflow][test] Fix edge case for same timestamp in ORM E2E test

- src/promptflow/promptflow/executor/_line_execution_process_pool.py
- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/unittests/processpool/test_line_execution_process_pool.py
Fix exec_line failed when line execution not start in bulk run scenario.
**Problem**
When processing input images, system errors may occur because the image path cannot be found. At this time, the flow has not started running, and the catch logic of the sub-process will cause an error: `Run record with ID '{run_id}' was not tracked in promptflow execution. ` causing this line to fail due to timeout, but in reality, the reason is that the image path cannot be found.
**Solution**
Call start_flow_run before handling exception to make sure the run_tracker has flow info.
> [PromptFlow][ProcessPool] Fix the logic of child process handling exception.

- src/promptflow-tools/tests/conftest.py
- src/promptflow-tools/tests/pytest.ini
- src/promptflow-tools/tests/test_embedding.py
- src/promptflow-tools/tests/test_handle_openai_error.py
- src/promptflow-tools/tests/test_open_source_llm.py
- src/promptflow-tools/tests/test_openai.py
- src/promptflow-tools/tests/test_serpapi.py
The function "skip_if_no_key" is used to skip the test if actual api key is not provided. To avoid misunderstanding, rename the function name from "skip_if_no_key" to "skip_if_no_api_key".
> Rename the function name from "skip_if_no_key" to "skip_if_no_api_key"

- .github/workflows/promptflow-sdk-cli-azure-e2e-test.yml
- docs/dev/replay-e2e-test-for-pfazure.md
- src/promptflow/tests/sdk_cli_azure_test/conftest.py
- src/promptflow/tests/sdk_cli_azure_test/recording_utilities/__init__.py
- src/promptflow/tests/sdk_cli_azure_test/recording_utilities/bases.py
- src/promptflow/tests/sdk_cli_azure_test/recording_utilities/constants.py
- src/promptflow/tests/sdk_cli_azure_test/recording_utilities/utils.py
This PR applies a rename to the test mode of pfazure tests. The three new modes are:
- **live**: real network traffic against live backend
- **record**: real network traffic against live backend, and recorded to YAML files
- **replay**: no real network traffic, interact with YAML files
This PR also includes a simple dev doc on this.
> [promptflow][fundamental] Rename environ name for pfazure test mode

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/promptflow/_utils/utils.py
- src/promptflow/tests/sdk_cli_test/unittests/test_run.py
Specify `ensure_ascii`/`force_ascii` to False when dump json, so that the dumped result can keep original format, instead of something like `\u65e5\u672c\u8a9e`.
> [promptflow][BugFix] Keep original format in run output file

- .github/workflows/tools_release_tag.yml
Fix the command about getting the latest tag. This command will provide the most recent tag according to the creation date from all tags ending with "-tools". 
**Fixed command:**
```bash
git tag -l '*-tools' | sort -V | tail -n 1
```
> Fix create_tools_release_tag release

- .github/actions/step_publish_test_results/action.yml
`pull_request` cannot use `secrets.GITHUB_TOKEN` to perform GH operations, commnet to bypass it.
This step targets to update status for check enforcer, however, we don't have a work one, so this step is not mandatory.
> [infrastructure] Bypass GH operation for status update

- src/promptflow/promptflow/_sdk/_serving/response_creator.py
- src/promptflow/promptflow/_sdk/_serving/swagger.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_serve.py
- src/promptflow/tests/test_configs/flows/chat_flow_with_stream_output/flow.dag.yaml
changes includes:
- add chat flow metadata into the swagger for client consumption
- besides the streaming start/end callback, add a new streaming event callback which will be used for tracking/collecting streaming response data
> [PFServing] add chat flow metadata in swagger and streaming event callback

- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/promptflow/_sdk/operations/_run_operations.py
- src/promptflow/promptflow/_sdk/operations/_run_submitter.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_run.py
This PR updates the way SDK/CLI dump inputs and outputs. After the run completed, SDK will collect and dump IO from debug info (flow artifacts folder), so that later SDK/CLI can directly read from that file; before that, SDK/CLI will get IO directly from debug info.
This change make image path absolute path in SDK/CLI, as the path is kept abs in debug info.
> [promptflow][BugFix] Make image path absolute path

- src/promptflow/promptflow/executor/batch_engine.py
- src/promptflow/tests/executor/e2etests/test_executor_with_image.py
- src/promptflow/tests/test_configs/flows/python_tool_with_composite_image/incomplete_inputs.jsonl
When submitting bulk run, if the default value of the image path is used, `FileNotFound` will be raised because the directory is not change to the flow working directory.  So we should change workinng dir when `exec_bulk`.
> [Bugfix][Executor] Change workinng dir when exec_bulk

- src/promptflow/promptflow/_utils/multimedia_utils.py
Replace `str(Path)` with `Path.as_posix()`.
> [promptflow] Use as_posix() instead of pure str()

- src/promptflow/promptflow/contracts/multimedia.py
- src/promptflow/tests/executor/unittests/contracts/test_multimedia.py
Fix the bug that pfbytes cannot be initialized with keyword args
Before this PR, we cannot use `Image(value=f.read())` to initialize an image object.
> [Bugfix][Contracts] Fix the bug that Image cannot be initialized with keyword args

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_core/tool_meta_generator.py
- src/promptflow/promptflow/_utils/tool_utils.py
- src/promptflow/promptflow/contracts/tool.py
- src/promptflow/promptflow/executor/_tool_resolver.py
- src/promptflow/tests/executor/unittests/_utils/test_tool_utils.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_tool.py
https://github.com/microsoft/promptflow/issues/714 asked support for kwargs.
Add `enable_kwargs` tag in tools.json for customer python tool.
Then clients could add corresponding support for kwargs by yaml authoring.
We don't need to modify execution logic to support kwargs.
Confirmed with @lalala123123 `_parse_tool_from_function` in `_sdk.operations._tool_operations.py` will not be used to generate meta.
> Add `enable_kwargs` tag in tools.json for customer python tool

- src/promptflow/tests/executor/unittests/executor/test_tool_resolver.py
- src/promptflow/tests/executor/unittests/processpool/test_healthy_ensured_process.py
Skip test `test_ensure_node_inputs_type` in Python 3.11 due to known enum issue.
> [promptflow][Test] Skip known enum issue in test when Python 3.11

- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/promptflow/_sdk/operations/_run_operations.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_run.py
If run status is failed, print error message; otherwise, user cannot know why the run is failed in SDK experience.
SDK experience:
CLI experience:
> [promptflow][BugFix] Print error message when run status is failed

- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_as_func.py
This PR removed AOAI connections in flow-as-func test to avoid transient connection invalid issue.
In that issue, the connection exists but open ai complains the endpoint/key is invalid.
> [Test][CI] Remove AOAI connections in flow-as-func test to avoid transient connection invalid issue

- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/tests/sdk_cli_test/unittests/test_local_storage_operations.py
In some cases, inputs line number may not have full set (e.g. line 1, 2, 4), so that we should not pad the outputs from line number 0. This PR updates the padding function parameter, so that padding will be applied according to the real line number.
> [promptflow][BugFix] Fix output padding when some inputs are missing

- src/promptflow/tests/_constants.py
- src/promptflow/tests/conftest.py
- src/promptflow/tests/sdk_cli_azure_test/conftest.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_cli.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_pf_client.py
- src/promptflow/tests/sdk_cli_global_config_test/conftest.py
- src/promptflow/tests/sdk_cli_global_config_test/e2etests/test_global_config.py
Developers can use below environment variables to customize Azure workspace for test:
- `PROMPT_FLOW_SUBSCRIPTION_ID`: subscription id
- `PROMPT_FLOW_RESOURCE_GROUP_NAME`: resource group name
- `PROMPT_FLOW_WORKSPACE_NAME`: workspace name
- `PROMPT_FLOW_RUNTIME_NAME`: runtime name `
If not specified, will use default workspace & runtime.
Also clean some unused fixtures.
> [promptflow][infrastructure] Make tests honor environment variables

- .github/workflows/create_promptflow_release_tag.yml
- scripts/release/promptflow-release-note.md
Update workflow [Create promptflow release tag](https://github.com/microsoft/promptflow/actions/workflows/create_promptflow_release_tag.yml) to also create a release for promptflow, which will be shown in [Releases](https://github.com/microsoft/promptflow/releases) page.
> [promptflow][fundamental] Update create tag workflow to also create a release

- src/promptflow/promptflow/_core/flow_execution_context.py
- src/promptflow/promptflow/_core/tool.py
- src/promptflow/promptflow/_core/tracer.py
- src/promptflow/promptflow/executor/_flow_nodes_scheduler.py
- src/promptflow/tests/executor/e2etests/test_executor_happypath.py
- src/promptflow/tests/test_configs/flows/async_tools/async_passthrough.py
- src/promptflow/tests/test_configs/flows/async_tools/flow.dag.yaml
In current implementation, pf assume all the tools are normal functions/methods.
When user provides an async function decorated by @tool, the behavior of pf would be strange.
In this PR, we checked the function type of the passed function, then go to a different call stack to ensure async function works well.
TODO: Currently if one async tool call another async tool, there would be no traces support. We need to adjust the logic to add such support.
> [Executor] Allow run async tools in executor

- src/promptflow/promptflow/_core/flow_execution_context.py
- src/promptflow/tests/conftest.py
In the previous PR, we forgot to set variant_id when moving the codes.
It is used in legacy contract to indicate the variants.
Added it back in this PR.
> [Bugfix] Add variant_id back for legacy runtime contract

- src/promptflow/promptflow/_core/tools_manager.py
1. Remove ValueError of `gen_dynamic_list` and `retrieve_tool_func_result` to unblock vectordb wrapper case:
1. The func has a required input.
2. The func is inside a wrapper.
Then the signature we get is wrapper's signature, when the required input provided, it's not in func signature:
2. Add log of func signature for better trouble shooting.
> Remove ValueError and add logs for gen_dynamic_list, retrieve_tool_unc_result

- .github/workflows/promptflow-sdk-pfs-e2e-test.yml
- src/promptflow/tests/sdk_pfs_test/conftest.py
- src/promptflow/tests/sdk_pfs_test/e2etests/test_run_apis.py
This PR targets to make workflow `promptflow-sdk-pfs-e2e-test` use `pull_request`, which means this workflow will not use any secrets in repo. Therefore, also update the run tests to use a flow that does not require any connection.
> [promptflow][Test] Make SDK PFS E2E use pull_request

- src/promptflow/promptflow/_sdk/operations/_local_azure_connection_operations.py
- src/promptflow/promptflow/azure/operations/_arm_connection_operations.py
When specifying workspace connection provider and get connection with secrets, sdk will call arm, this path does not requires create pf azure client, as pf azure client creation requires workspace read permission.
> [Connection] Refine workspace connection to require limited permission

- examples/flows/integrations/README.md
- examples/flows/standard/web-classification/README.md
(https://github.com/microsoft/promptflow/issues/1096)
Integrations folder contains flow examples contributed by various contributors. Each flow example should have a README.md file that provides a comprehensive introduction to the flow and includes contact information for the flow owner.
> [Example] Add flow integrations folder and readme.md

- .github/workflows/samples_configuration.yml
- .github/workflows/samples_flowinpipeline_pipeline.yml
- .github/workflows/samples_getstarted_flowasfunction.yml
- .github/workflows/samples_getstarted_quickstart.yml
- .github/workflows/samples_getstarted_quickstartazure.yml
- .github/workflows/samples_runmanagement_cloudrunmanagement.yml
- .github/workflows/samples_runmanagement_runmanagement.yml
- .github/workflows/samples_tutorials_e2e_development_chat_with_pdf.yml
- .github/workflows/samples_tutorials_flow_deploy_azure_app_service.yml
- .github/workflows/samples_tutorials_flow_deploy_distribute_flow_as_executable_app.yml
- .github/workflows/samples_tutorials_flow_deploy_docker.yml
- .github/workflows/samples_tutorials_flow_deploy_kubernetes.yml
- .github/workflows/samples_tutorials_flow_fine_tuning_evaluation_promptflow_quality_improvement.yml
- scripts/readme/workflow_generator.py
`examples/flows/integrations` folder tagrtes to be 3P contributed examples folder, we shouldn't apply workflow covering this.
- Updated all existing workflows, triggered/founded in #1097 
- Update the workflow generator
> [fundamental] Exclude examples/flows/integrations from workflows

- .github/workflows/samples_configuration.yml
- .github/workflows/samples_flowinpipeline_pipeline.yml
- .github/workflows/samples_getstarted_flowasfunction.yml
- .github/workflows/samples_getstarted_quickstart.yml
- .github/workflows/samples_getstarted_quickstartazure.yml
- .github/workflows/samples_runmanagement_cloudrunmanagement.yml
- .github/workflows/samples_runmanagement_runmanagement.yml
- .github/workflows/samples_tutorials_e2e_development_chat_with_pdf.yml
- .github/workflows/samples_tutorials_flow_deploy_azure_app_service.yml
- .github/workflows/samples_tutorials_flow_deploy_distribute_flow_as_executable_app.yml
- .github/workflows/samples_tutorials_flow_deploy_docker.yml
- .github/workflows/samples_tutorials_flow_deploy_kubernetes.yml
- .github/workflows/samples_tutorials_flow_fine_tuning_evaluation_promptflow_quality_improvement.yml
- scripts/readme/workflow_generator.py
Fix typo (missing s) introduced in #1176
> [example][fundamental] Fix typo for exclude path

- docs/README.md
fix broken doc links in docs folder readme.
> fix broken doc links in docs folder readme

- .github/workflows/promptflow-executor-e2e-test.yml
- .github/workflows/promptflow-executor-unit-test.yml
- .github/workflows/promptflow-global-config-test.yml
- .github/workflows/promptflow-replay-test.yml
- .github/workflows/promptflow-sdk-cli-test.yml
- .github/workflows/promptflow-sdk-pfs-e2e-test.yml
- .github/workflows/sdk-cli-azure-test.yml
This PR updates listen path for several workflows triggered during PR:
- `scripts/**` to `scripts/building/**`
- use abs path for workflow YAML file
So that we won't trigger many workflows when update `scripts` folder.
> [promptflow][fundamental] Loose path for CI workflows

- src/promptflow/promptflow/batch/_batch_engine.py
This PR introduces a new property `batch_run_source` to the `OperationContext` to better differentiate the data source for batch runs. A new Enum class `BatchRunSource` with two enums `Run` and `Data` has been defined. The `run` interface of the `BatchEngine` object now checks the `input_dirs` parameter to determine if the batch run is sourced from a previous run or raw data. If `run.outputs` is present in `input_dirs`, the `batch_run_source` is set to `BatchRunSource.Run`, otherwise, it is set to `BatchRunSource.Data`. This enhancement facilitates improved tracking and handling of batch run sources.
> Add `batch_run_source` property to `OperationContext` for better batch run source insight

- src/promptflow/promptflow/executor/_line_execution_process_pool.py
- src/promptflow/tests/executor/unittests/processpool/test_line_execution_process_pool.py
**Problem**
The wait() method of starmap_async only waits for the result and does not capture exceptions.
**Solution**:
Use async_result.get() to propagate exceptions if they are raised.
> [PromptFlow] Fix can't raise exception in processpool's run.

- src/promptflow/promptflow/_core/operation_context.py
- src/promptflow/promptflow/batch/_batch_engine.py
- src/promptflow/promptflow/batch/_batch_inputs_processor.py
- src/promptflow/tests/executor/unittests/_core/test_operation_context.py
This PR introduces a new interface within `OperationContext` to infer the source of batch input through an input mapping dictionary. This dictionary maps each input to its corresponding data source, providing a unified method for external calls and simplifying management of future changes. The interface encapsulates and extends the logic initially implemented in PR #1223, offering a more streamlined approach to handling input source references.  
By abstracting this functionality into a dedicated interface, we improve the maintainability and readability of the codebase. This change is intended to allow other components of the system to more easily integrate with the input source inference process without needing to understand the underlying mapping logic.
> Introduce Interface for Batch Input Source Inference on OperationContext 

- src/promptflow/tests/executor/e2etests/test_image.py
- src/promptflow/tests/test_configs/flows/chat_flow_with_image/mock_chat.py
Add plain text in chat response.
Refine assert logic in test code, `assert_contain_image_reference` can't raise exception when there doesn't exist image.
_If there is no image reference, say just strings in a list. The method will not raise exception_
> Improve image test case

- src/promptflow/promptflow/_utils/execution_utils.py
- src/promptflow/promptflow/batch/_batch_inputs_processor.py
- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/unittests/_utils/test_execution_utils.py
- src/promptflow/tests/executor/unittests/batch/test_batch_inputs_processor.py
- src/promptflow/tests/executor/unittests/executor/test_flow_executor.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_run.py
- src/promptflow/tests/test_configs/flows/default_input/flow.dag.yaml
- src/promptflow/tests/test_configs/flows/default_input/test_print_aggregation.py
- src/promptflow/tests/test_configs/flows/default_input/test_print_input.py
To apply default value correctly, we need to check if default value is None or not.
Previous logic will not apply `False`/`[]`/`{}` from default value.
Behavior changes:
* <a href="diffhunk://#diff-113cef506fb37cf3588f2246fec675adec478ddd47b9de5b246778fc8d03f23cL14-R14">`src/promptflow/promptflow/_utils/execution_utils.py`</a>: Updated the condition for checking if a key is not in `updated_inputs` and has a default value to also check if the default value is not `None`.
* <a href="diffhunk://#diff-faa6c81d614b7e41b18a42a93139d961d92afa9aa9dd0b72cb6b7176d7541e69L585-R585">`src/promptflow/promptflow/executor/flow_executor.py`</a>: Updated the condition in the `_apply_default_value_for_aggregation_input` method to consider only inputs with non-None default values.
* …
> Fix default value apply logic.

- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/e2etests/test_executor_happypath.py
- src/promptflow/tests/test_configs/flows/llm_tool/echo.py
- src/promptflow/tests/test_configs/flows/llm_tool/flow.dag.yaml
- src/promptflow/tests/test_configs/flows/llm_tool/joke.jinja2
We only injected openai api when initializing `Executor` previously, but when running a single node run, it wasn't injected due to no need to create an `Executor`, so we should also inject openai api in single node run.
> [Executor] Inject openai api in single node run

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/storage/_sqlite_client.py
- src/promptflow/setup.py
This PR targets to bump `SQLAlchemy` to 2.x. Different from #1254 , use local import to remove dependency to `dataset`.
> [promptflow] Bump SQLAlchemy to 2.x using local import

- src/promptflow/promptflow/_core/operation_context.py
This pull request to `src/promptflow/promptflow/_core/operation_context.py` fixes an issue where the user agent string was starting with a space in the `OperationContext` class. Two changes were made in the `append_user_agent` method and the `parts` function to ensure that the user agent string does not start with a space.
* <a href="diffhunk://#diff-9178fcc0ca6dea0124a2a13bb8e734a77ffbc4baadfe29d18a366452ff8f865aR130-R132">`src/promptflow/promptflow/_core/operation_context.py`</a>: Fixed an issue where the user agent string was starting with a space in the `OperationContext` class. <a href="diffhunk://#diff-9178fcc0ca6dea0124a2a13bb8e734a77ffbc4baadfe29d18a366452ff8f865aR130-R132">[1]</a> <a href="diffhunk://#diff-9178fcc0ca6dea0124a2a13bb8e734a77ffbc4baadfe29d18a366452ff8f865aL111-R114"> …
> [SDK]fix leading space in UA

- src/promptflow/promptflow/_core/_errors.py
- src/promptflow/promptflow/_core/tools_manager.py
- src/promptflow/tests/executor/unittests/_core/test_tools_manager.py
For tool's **init parameter**, we only accept literal value. (Flow input or node reference should not be used)
Change error type to user error and improve error message.
> Raise user error for non literal value for init parameter

- src/promptflow/promptflow/_sdk/_utils.py
- src/promptflow/promptflow/_sdk/operations/_flow_operations.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_local_operations.py
- src/promptflow/tests/test_configs/flows/web_classification_invalid/convert_to_dict.py
- src/promptflow/tests/test_configs/flows/web_classification_invalid/flow.dag.yaml
This pull request includes various changes to improve the functionality and structure of the codebase. The most important changes include adding a new test method to test the behavior of a specific method, updating a method to use a new type and adding a new parameter, and adding a new Python file with a function for parsing JSON.
Perf change:
- e2e time for pfutil command: ~10.10s => 5.74s (cut for 44%)
- Measure-Command { C:\Users\yangtongxu\AppData\Local\miniconda3\envs\py39_promptflow\python.exe c:\Users\yangtongxu\.vscode\extensions\prompt-flow.prompt-flow-1.5.0\pfutil\pfutil.py tool -f hello.py -wd c:\Users\yangtongxu\code\promptflow\examples\flows\standard\basic-with-connection -o c:\Users\yangtongxu\code\promptflow\examples\flows\standard\basic-with-connection\.promptflow\flow.tool …
> feat: tool meta generation perf optimization

- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/promptflow/batch/_csharp_executor_proxy.py
This pull request includes changes to improve the functionality and maintainability of the codebase. The most important changes include adding a new method to the `ExecutorProxy` class and modifying the import statement in the `_csharp_executor_proxy.py` file, as well as updating the `load_inputs_and_outputs` method in the `_local_storage_operations.py` file to use a constant instead of a string.
Main changes:
* <a href="diffhunk://#diff-f8219170007d8a89eed104a166ab8c0c9d3af5b5c5e61225659d982f470aeb95R60-R81">`src/promptflow/promptflow/batch/_csharp_executor_proxy.py`</a>: Added a new method `exec_line_async` to the `ExecutorProxy` class and modified the import statement to include the `LineResult` class. <a href="diffhunk://#diff-f8219170007d8a89eed104a166ab8c0c9d3af5b5c5e61225659d982f470 …
> fix: `run show-details` depends on inputs line number

- src/promptflow/promptflow/_cli/_params.py
- src/promptflow/promptflow/_cli/_pf/_config.py
- src/promptflow/promptflow/_cli/_pf/_connection.py
- src/promptflow/promptflow/_cli/_pf/_flow.py
- src/promptflow/promptflow/_cli/_pf/_run.py
- src/promptflow/promptflow/_cli/_pf/_tool.py
- src/promptflow/promptflow/_cli/_pf/entry.py
- src/promptflow/promptflow/_cli/_pf_azure/_connection.py
- src/promptflow/promptflow/_cli/_pf_azure/_flow.py
- src/promptflow/promptflow/_cli/_pf_azure/_run.py
- src/promptflow/promptflow/_cli/_pf_azure/entry.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
This pull request includes various changes to improve the codebase and enhance functionality. The most important changes include adding a new test method to verify the parsing of the user agent string, replacing the `logging_params` list with `base_params` in multiple files to align with other parts of the codebase, and reorganizing and formatting imports for better readability.
Main changes:
* <a href="diffhunk://#diff-7d74ecb42a689e4b7dea2171b91f90db56f79b6efcd70629df1548a1b091f229R1585-R1601">`src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py`</a>: Added a new test method to verify the parsing of the user agent string.
* <a href="diffhunk://#diff-dcf2294774837d1f40eae9676737cb8c50f6ac940b7c1392660d17d64a84b93aR9-L12">`src/promptflow/promptflow/_cli/_pf/_flow.py`</a>: Replaced the …
> [CLI] Add param "--user-agent" in CLI

- src/promptflow/promptflow/_core/tool_meta_generator.py
- src/promptflow/promptflow/executor/_errors.py
- src/promptflow/tests/executor/unittests/_utils/test_generate_tool_meta_utils.py
- src/promptflow/tests/executor/unittests/executor/test_tool_resolver.py
For `TemplateSyntaxError` from jinja package, add line number info in error message.
Need to add this info for 2 scenarios (meta generation and tool resolve)
> Add line number info in error message when failed to parse jinja template.

- src/promptflow/promptflow/_utils/multimedia_utils.py
- src/promptflow/tests/executor/unittests/_utils/test_multimedia_utils.py
Fix exception definition for loading image from url.
Previous logic didn't use `message_format` in right way.
Will throw exception as we try to get error message and lose the actual error info in portal scenario.
> Fix exception definition for loading image from url.

- src/promptflow/promptflow/_sdk/entities/_flow.py
This pull request simplifies the code in the `src/promptflow/promptflow/_sdk/entities/_flow.py` file by removing an unnecessary import statement and changing how the `invoker` object is created. Instead of using the `FlowContextResolver.resolve()` method, the `invoke()` method is called directly on `self` with the `inputs` parameter.
Main code simplification:
* <a href="diffhunk://#diff-339752a6e9c04159a62708efed6b385bd91b016a0f0d2edeb32024fd19886a2bL303-R307">`src/promptflow/promptflow/_sdk/entities/_flow.py`</a>: Removed the import statement for `FlowContextResolver` and changed the creation of the `invoker` object to directly call the `invoke()` method on `self` with the `inputs` parameter.
> feat: enable function call for csharp flow

- src/promptflow/promptflow/_sdk/_submitter/test_submitter.py
- src/promptflow/promptflow/_utils/async_utils.py
- src/promptflow/promptflow/batch/_batch_engine.py
- src/promptflow/promptflow/contracts/flow.py
This pull request to the `src/promptflow` directory includes several modifications to improve the codebase. The most important changes include modifying the `_batch_engine.py` file to use the `async_run_allowing_running_loop` function, adding a comment to suggest refactoring the `_set_tool_loader` method in `flow.py`, and modifying the `test_submitter.py` file to remove unused imports and replace the use of `asyncio.run` with the `async_run_allowing_running_loop` function.
Main code changes:
* <a href="diffhunk://#diff-ecf0905f2116abe08b5cf2931b856bf39aa8b38a30fadd9042538d076dbfde80L138-L152">`src/promptflow/promptflow/batch/_batch_engine.py`</a>: Modified code to use the `async_run_allowing_running_loop` function for running the batch in a new thread or the current thread. Removed the …
> fix: enable function call for csharp flow in notebook

- src/promptflow/promptflow/_cli/_pf_azure/entry.py
- src/promptflow/promptflow/_cli/_utils.py
- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_cli_with_azure.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_cli.py
- src/promptflow/tests/test_configs/recordings/test_cli_with_azure_TestCliWithAzure_test_cli_telemetry.yaml
This pull request includes changes related to adding telemetry logging with custom dimensions for workspace information in the PromptFlow Azure CLI. The most important changes include adding a new function `_get_workspace_info(args)` and modifying the `entry` function in `_pf_azure/entry.py` to support telemetry logging, as well as adding an import statement for the `contextlib` module and a new test method `test_cli_telemetry` in `test_cli_with_azure.py` to verify the correctness of telemetry logging.
Main changes:
* <a href="diffhunk://#diff-3f1dd7459115086f5d3af3d298744079416aebf0a0a99d19883591e7e053cf19R91-R102">`src/promptflow/promptflow/_cli/_pf_azure/entry.py`</a>: Added a new function `_get_workspace_info(args)` and modified the `entry` function to support telemetry logging with …
> [SDK] Add workspace info in CLI telemetry

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_sdk/operations/_run_operations.py
#1354 mentions that logs can lead to large visualize HTML file and browser cannot open. As we do not provide logs view in visualize page, empty the logs field as work around.
> [promptflow][BugFix] Empty logs in visualize HTML to avoid large file

- src/promptflow/promptflow/_sdk/data/docker/Dockerfile.jinja2
When build the docker image, the whole `flow` directory is added to docker image before installing the dependencies (python and debian packages, etc). However any minor changes results in re-installing the dependencies. To avoid the unneccessary time-consuming installation, only copy the `requirements.txt` that's required by `pip install` first, and then install the depedencies.
> Optimise docker image build: copy python requirements file only before install them

- .github/workflows/stale.yml
This PR targets to leverage [actions/stale](https://github.com/actions/stale) to add label for stale issue/PR.
In short, issue will be tagged label `no-recent-activity` after 30 days, and stale PR will be tagged after 7 days. Issues with label `long-term` will be excluded.
**References**
- Azure SDK stale issue: <https://github.com/Azure/azure-sdk-for-python/issues/32959>
- Azure SDK stale pull request: <https://github.com/Azure/azure-sdk-for-python/pull/32182>
> [Fundamental] Introduce stale for issue/PR status monitor

- .github/workflows/stale.yml
This PR targets to refine stale workflow:
- Increase `operations-per-run`: according to https://github.com/microsoft/promptflow/actions/runs/7120514752, in our scenario, we need to increase this limit.
- Exclude PR with label `long-term`.
> [Fundamental] Refine stale workflow: Increase operations-per-run and exclude long-term PR

- src/promptflow/tests/executor/unittests/_utils/test_exception_utils.py
This is to fixing the failing test: test_reference_code under python 3.11
> Fixing the enum related failing test under python 3.11

- src/promptflow/tests/executor/unittests/processpool/test_line_execution_process_pool.py
On macOS, the default process start method is spawn after version 3.8. 
Set the process start method to fork on macOS.
[Related Link](https://docs.python.org/3/library/multiprocessing.html#:~:text=Changed%20in%20version%203.8%3A%20On%20macOS%2C%20the%20spawn%20start%20method%20is%20now%20the%20default.%20The%20fork%20start%20method%20should%20be%20considered%20unsafe%20as%20it%20can%20lead%20to%20crashes%20of%20the%20subprocess%20as%20macOS%20system%20libraries%20may%20start%20threads.%20See%20bpo%2D33725.)
> [PromptFlow] Set the process startup mode to fork on Mac.

- src/promptflow/promptflow/_cli/_pf/entry.py
- src/promptflow/promptflow/_cli/_pf_azure/entry.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
This pull request includes changes to improve the behavior and user experience of the CLI tool. The most important changes include adding function calls to display a privacy statement and a welcome message, appending `"-h"` to the `command_args` list when only one command argument is provided, and adding new test methods to verify the behavior of the CLI tool.
Before:
After:
Main functionality changes:
* <a href="diffhunk://#diff-3f1dd7459115086f5d3af3d298744079416aebf0a0a99d19883591e7e053cf19R133-R137">`src/promptflow/promptflow/_cli/_pf_azure/entry.py`</a>: Added function calls to display a privacy statement and a welcome message before showing the help message when no command arguments are provided.
* <a href="diffhunk://#diff-b8db1e22a2a3f1affd6de96bc94ffee0363fb5a80a1b3452e5fd6926ce7a …
> [CLI] Show help instead of failing when calling 'pf run".

- src/promptflow/promptflow/executor/_async_nodes_scheduler.py
- src/promptflow/promptflow/executor/flow_executor.py
This is the initial version to run mixed async/sync tools in async scheduler, it is only enabled when all tools are async or the environment variable `PF_USE_ASYNC` is set for debugging purpose.
This pull request introduces new functionality to execute synchronous tools in a separate thread using a thread pool executor in the `AsyncNodesScheduler` class. It also modifies the condition in the `_traverse_nodes` method of the `FlowExecutor` class to check if all values in the `_tools` dictionary are coroutine functions or if the `PF_USE_ASYNC` environment variable is set to "true", indicating that the flow should be executed in async mode.
Main functionality changes:
* <a href="diffhunk://#diff-aea06244ab378a5cbd47d27ba6d92c433df3089d077871b1e6aaa1b47cd3c73fR36-R55">`src/promptflow/promptflow …
> [Executor] Initial version of mixed async/sync tools in async scheduler

- .github/workflows/samples_configuration.yml
- scripts/readme/workflow_generator.py
Example `configuration.ipynb` is very unique among examples in this repo, it targets to demonstrate how to setup an Azure ML workspace, and not related to prompt flow at all; and it locates in `examples/`. Update the workflow generation logic to make an exception for it: just listen to its notebook and workflow, that's all.
> [example][bugfix] Make configuration example exception in workflow generation

- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/_submitter/test_submitter.py
- src/promptflow/promptflow/_sdk/_submitter/utils.py
- src/promptflow/promptflow/_sdk/entities/_flow.py
- src/promptflow/promptflow/_sdk/operations/_flow_operations.py
- src/promptflow/promptflow/batch/_base_executor_proxy.py
- src/promptflow/promptflow/batch/_csharp_executor_proxy.py
- src/promptflow/promptflow/batch/_python_executor_proxy.py
- src/promptflow/tests/executor/unittests/_utils/test_connection_utils.py
This pull request includes several changes to improve code readability, maintainability, and functionality. The most important changes include refactoring code in the `_flow_operations.py` file to improve readability and maintainability, various changes in the `utils.py` file to improve code clarity and future modifications, and the addition of a new class method in the `_base_executor_proxy.py` file for generating tool metadata.
Code readability and maintainability improvements:
* <a href="diffhunk://#diff-afdd40a5d0519512dcf9be48bd46c4caaa2291b808687de77896989af63f47e4L372-R391">`src/promptflow/promptflow/_sdk/operations/_flow_operations.py`</a>: Refactored code to improve readability and maintainability by using the `load_flow` function instead of directly instantiating classes. <a …
> feat: correct the way to get used connection names for csharp

- .github/workflows/stale.yml
This PR updates stale items cleanup workflow to enable close. Issues and PRs will be closed after 7 days after tagged `no-recent-activity` label, and bot will comment a message in PR.
> [fundamental] Enable close stale items

- .github/workflows/tools_tests.yml
By abusing the "pull_request_target" event for triggering workflows, any GitHub user can create a Pull Request from a Fork against this repository and the action will execute. There is a step in the workflow that runs the following code:
``` python
python ./scripts/tool/generate_connection_config.py --tenant_id ${{ secrets.TENANT_ID }} --client_id ${{ secrets.CLIENT_ID }} --client_secret ${{ secrets.CLIENT_SECRET }}
```
This means that an attacker can create a Fork with a modified generate_connection_config.py that will be executed, and has credentials passed in as a parameter, making it trivial to dump these credentials out, so add the authorize step.
The authorize step appears to be used as a preliminary job to determine the context in which the workflow is being executed, specifically …
> Add authorize step to tool_tests.yml

- src/promptflow/promptflow/executor/_async_nodes_scheduler.py
In current implementation, there is a bug that uses legacy code reference of flow execution context which introduce a bug when running sync function in async mode.
This pull request to `src/promptflow/promptflow/executor/_async_nodes_scheduler.py` simplifies the code by removing the `_invoke_sync_tool` method from the `AsyncNodesScheduler` class and delegating the responsibility of invoking the tool to the `context` object.
* <a href="diffhunk://#diff-aea06244ab378a5cbd47d27ba6d92c433df3089d077871b1e6aaa1b47cd3c73fL104-R112">`src/promptflow/promptflow/executor/_async_nodes_scheduler.py`</a>: Removed the `_invoke_sync_tool` method from the `AsyncNodesScheduler` class and replaced it with a call to the `invoke_tool` method of the `context` object.
> [Executor] Fix bug when sync node is called in async mode

- src/promptflow/promptflow/executor/_async_nodes_scheduler.py
Update ThreadPoolExecutor finalization logic in async scheduler to ensure cancel works if it is running.
This pull request to `src/promptflow/promptflow/executor/_async_nodes_scheduler.py` improves the handling of `ThreadPoolExecutor` by manually shutting it down after tasks are completed, ensuring that the cancellation error is raised immediately.
* <a href="diffhunk://#diff-aea06244ab378a5cbd47d27ba6d92c433df3089d077871b1e6aaa1b47cd3c73fL38-R47">`src/promptflow/promptflow/executor/_async_nodes_scheduler.py`</a>: Removed the `with` statement and assigned the `ThreadPoolExecutor` to a variable to manually shutdown the executor after tasks are completed, ensuring immediate raising of the cancellation error.
> [Executor] Update executor finalization in async scheduler

- scripts/building/check_enforcer.ps1
Promptflow-tool is blocked by promptflow enforcer matcher
> [Fundamental] Promptflow-tool is blocked by promptflow enforcer matcher

- src/promptflow/promptflow/_sdk/_utils.py
This code gives error when creating azure runs under multi-thread context:
`for entry_point in pkg_resources.iter_entry_points(group=PACKAGE_TOOLS_ENTRY):`
TypeError: 'NoneType' object is not callable
The reason could be `pkg_resources` get loaded both inside the function and outside it.
> [SDK/CLI] Fix error when creating azure run in multi-thread context

- src/promptflow/tests/conftest.py
- src/promptflow/tests/sdk_cli_azure_test/conftest.py
- src/promptflow/tests/sdk_cli_azure_test/recording_utilities/__init__.py
- src/promptflow/tests/sdk_cli_azure_test/recording_utilities/bases.py
In Azure tests, we have some fixtures that create flow/run for tests. **IDEALLY** we can make them package scope, so that all tests can share them - only create once and always reuse, time-saving, efficient; **however**, replay tests require function scope because replay tests need test function info to locate the recording YAML.
This PR leverages dynamic scope fixtures to resolve this: in live mode, make those fixtures package scope, so that tests can reuse; in record and replay mode, keep function scope as before. Then, we can still enjoy replay tests and benefit shared fixtures during live tests. Cheers!
**Experiment/Proof**
Manually triggered a live test: <https://github.com/microsoft/promptflow/actions/runs/7258746460>, and from corresponding workspace, there are only 4 failed run …
> [promptflow][fundamental] Make Azure test fixtures package scope when live mode

- .github/workflows/labeler.yml
This PR adds one step in workflow [Pull Request Labeler](https://github.com/microsoft/promptflow/actions/workflows/labeler.yml) to apply a label (current value: `external`) to pull request from fork, then we can use this label to query PRs from fork easily.
Some experiments from private repo:
- fork PR: https://github.com/zhengfeiwang/gh-actions/pull/9
- internal PR: https://github.com/zhengfeiwang/gh-actions/pull/10
> [fundamental] Update PR labeler workflow to apply a label to PR from fork

- .github/workflows/sdk-cli-perf-monitor-test.yml
[SDK perf monitor CI](https://github.com/microsoft/promptflow/actions/workflows/sdk-cli-perf-monitor-test.yml) always uses replay mode, so it should be safe to remove steps that related to sensitive data: Azure CLI login and prepare live resources (replace with copy connection json example as a mock); otherwise, these steps will fail in a PR from fork as it does not have enough permission to do so.
Also make workflow listen to change to itself.
> [fundamental][bugfix] Remove useless steps in perf monitor CI

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_sdk/_submitter/test_submitter.py
- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/e2etests/test_image.py
Change node test's interface. Add storage to persist image.
Storage is a more flexible way to persist run info.
Using storage, we could apply same logic to implement async flow test and node test.
Didn't delete `output_sub_dir` because we may need to keep backward combability for a few versions.
> Change node test's interface. Add storage to persist image.

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/tests/sdk_cli_test/unittests/test_utils.py
This PR targets to support the feature ask in #1501 , user can configure PF home directory via setting environment variable `PF_HOME_DIRECTORY` in case they don't have enough permission to operate the default value (`~/.promptflow/`).
> [promptflow][feature] Support to configure PF home directory

- src/promptflow/promptflow/_sdk/_configuration.py
- src/promptflow/promptflow/_sdk/_utils.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
- src/promptflow/tests/sdk_cli_test/unittests/test_config.py
This PR supports config user agent for 1p customer to help us distinguish usage in telemetry.
This pull request includes changes to the codebase that improve the user agent functionality and add new tests for the user agent configuration.
Main user agent changes:
* <a href="diffhunk://#diff-47208ac35b30920275fcd5e55d662647ef360129359bdc77fddd2a2157b6f47eR887-R908">`src/promptflow/promptflow/_sdk/_utils.py`</a>: Added a new class method `update_user_agent_from_config` to the `ClientUserAgentUtil` class that retrieves the user agent from the configuration and appends it to the existing user agent.
* <a href="diffhunk://#diff-ff53f9e2ad1838023fb07cafd5526a639fe9589e470f9983a74 …
> [SDK] Support "pf config set user_agent="smile-llm/0.0.1""

- src/promptflow/promptflow/_utils/_errors.py
- src/promptflow/promptflow/_utils/multimedia_utils.py
- src/promptflow/promptflow/contracts/_errors.py
- src/promptflow/promptflow/executor/_tool_resolver.py
- src/promptflow/tests/executor/unittests/_utils/test_multimedia_utils.py
- src/promptflow/tests/executor/unittests/executor/test_tool_resolver.py
This pull request includes changes to improve test coverage and handle empty image inputs in the `multimedia_utils` module. The most important changes include adding test cases for the `load_multimedia_data` and `create_image` functions, and modifying the exception handling for empty image inputs.
Summary of changes:
* <a href="diffhunk://#diff-032d36cff1825e9647e49a6c988fc63557a7a02df06ba02ff5b850f0d5a6d4ceR196-R201">`src/promptflow/tests/executor/unittests/_utils/test_multimedia_utils.py`</a>: Added test cases to improve test coverage for `load_multimedia_data` and `create_image` functions. <a href="diffhunk://#diff-032d36cff1825e9647e49a6c988fc63557a7a02df06ba02ff5b850f0d5a6d4ceR196-R201">[1]</a> <a href="diffhunk://#diff-032d36cff1825e9647e49a6c988fc63557a7a02df06ba02ff5b850f0d5a6d4ceL …
> Improving error handling for invalid image inputs

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_core/flow_execution_context.py
- src/promptflow/promptflow/_core/run_tracker.py
- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/test_configs/flows/async_tools_with_sync_tools/async_passthrough.py
- src/promptflow/tests/test_configs/flows/async_tools_with_sync_tools/flow.dag.yaml
When received SIGINT in a running flow with both sync(wrapped as coroutine) and async nodes:
1. Cancel async node, enter node asyncio.Canceled error handling logic.
2. Cancel flow run.
3. Persist status of async node and flow to Canceled. There's bug that the async node's status is still Running, working on fix.
4. Wait for sync node to finish. Here we rely on external timer and kill mechanism to avoid long-running useless job.
> Handle cancellation of async flow test and node test

- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_serve.py
In flow serving tests, remove `flow_serving_client` fixture requst in `@pytest.mark.usefixtures` as it will be requests in the test function parameters. Otherwise, we might run into local connection not found error, which shall result from `setup_local_connection` has not been requested.
> [promptflow][bugfix] Adjust fixture order to fix breaking flow serve test

- src/promptflow/promptflow/_sdk/_submitter/run_submitter.py
This pull request includes a single change to the file `src/promptflow/promptflow/_sdk/_submitter/run_submitter.py`. The change adds a new condition to log a warning message if the `error_logs` variable is not empty in the `_submit_bulk_run` method. This change provides more information to the user.
Main change:
* <a href="diffhunk://#diff-e3499cf713c66612d91723759de1c5076c22689b2ce2c89678f82de624b57c2cR114">`src/promptflow/promptflow/_sdk/_submitter/run_submitter.py`</a>: Added a new condition to log a warning message if `error_logs` is not empty in the `_submit_bulk_run` method.
> [SDK] Fix extra warning for batch run

- .github/workflows/sdk-cli-perf-monitor-test.yml
- src/promptflow/promptflow/_cli/_pf/entry.py
- src/promptflow/promptflow/_cli/_pf_azure/entry.py
- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_azure_cli_perf.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli_perf.py
After using replay mode
The time consumption of "**pf.azure.create**" related commands will be reduced, with an average time of 6 seconds, but the maximum time consumption is still 20 seconds+
The duration of other commands PC99 is less than 10 seconds, but the maximum duration is still 20 seconds+
This PR modifies the test mode to replay mode and reduces the time limit, and then continues to observe the average and maximum time consumption, PC99 time consumption.
> update cli perf time limit

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_core/run_tracker.py
- src/promptflow/tests/executor/unittests/_core/test_run_tracker.py
Add top-level api_calls in flow trace to aggregate flow level information.
The current implementation uses hard-coded top level fields instead of using flow-level Trace object, that's due to the implementation of current Tracer does not support multiple level activation due to the difficulty of supporting concurrency.
Example effect on web_classification flow:
Before:
After:
> [Executor] Add root level api_calls

- src/promptflow/promptflow/_core/tracer.py
- src/promptflow/promptflow/contracts/trace.py
- src/promptflow/tests/executor/unittests/_core/test_tracer.py
* Refactored the `Tracer` class by extracting a new `_create_trace_from_function_call` method.
* Added test cases for the newly created method.
The test cases are named according to the policies described in [this post](https://enterprisecraftsmanship.com/posts/you-naming-tests-wrong/).
TLDR:
> Name the test as if you were describing the scenario to a non-programmer who is familiar with the problem domain.
Below are the test case names:
This pull request includes changes to improve the behavior and readability of the codebase. The most important changes include adding new functions and a test class for testing the behavior of a specific function in the `test_tracer.py` file, modifying the `push_tool` method in the `Tracer` class to improve code readability and reusability, and adding a …
> Refactor Tracer and add more unit tests

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/executor/_async_nodes_scheduler.py
- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/test_configs/flows/async_tools_with_sync_tools/async_passthrough.py
- src/promptflow/tests/test_configs/flows/async_tools_with_sync_tools/flow.dag.yaml
Exit the process if all async tools are done or exceeds wait timeout after received SIGINT or SIGTERM.
This is particularly useful when user press ctrl-c to cancel a flow with mixed sync and async nodes, in which case the sync node will run in a thread that is not killed by the signal and blocks the process from exiting.
> [Executor] Exit the process when all async tools are done or exceeded timeout after cancellation

- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_run.py
Newly added test `test_get_details_against_partial_completed_run` is flaky, it will fail due to line run timeout, a known executor bug with fork mode. To work around it before executor switch to default spawn mode, add a patch decorator to force spawn mode for this test.
> [promptflow][bugfix] Fix flaky test due to fork mode

- src/promptflow/promptflow/_utils/multimedia_utils.py
- src/promptflow/promptflow/contracts/multimedia.py
- src/promptflow/tests/executor/unittests/_utils/test_multimedia_utils.py
This pull request includes changes related to determining the mime type of image object when initializing Image object. Previously, we determine the mime type before initializing image object, and pass the mime type to create an image, which caused some duplicated code, because we may have multiple code path need to detemine mime type and create image, therefore, in this PR, we moved the mime type guessing to the `__init__` function of Image class to avoid duplicated code.
Main changes:
* <a href="diffhunk://#diff-46760b7ed265c4b29c9cc4111fb19da9b815717e4d7180f61e0d0da023d2a8f9L66-L87">`src/promptflow/promptflow/_utils/multimedia_utils.py`</a>: Removed functionality for determining MIME type.
* <a href="diffhunk://#diff-201a9347f2427df518f6053cf652aa1880a430ea98655c265c49df17037ac735R2">`s …
> Guess mime type when init Image

- src/promptflow/promptflow/batch/_batch_engine.py
Enable PF_WORKER_COUNT when creating semaphore
> [Internal][Executor] Enable PF_WORKER_COUNT when creating semaphore

- src/promptflow/promptflow/contracts/multimedia.py
- src/promptflow/tests/executor/unittests/contracts/test_multimedia.py
Fix bug when guessing mime type. When loading image, we use `filetype.guess_mime` to guess mime type, if failed to recognize the mime type, it will return none, so we should check the return value before referring it.
> Fix bug when guessing mime type

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/promptflow/_sdk/operations/_run_operations.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_run.py
- src/promptflow/tests/test_configs/flows/flow-with-nan-inf/flow.dag.yaml
- src/promptflow/tests/test_configs/flows/flow-with-nan-inf/nan_inf.py
`-Infinity`, `Infinity` and `NaN` are not valid JSON value, and they will lead to JavaScript parse error (raised in #1516 ). This PR targets to fix this by converting them to string during visualize operation (aligned behavior to PFS/portal experience), leveraging `parse_constant`.
This pull request includes various changes to improve the functionality and usability of the codebase. The most important changes include adding a new parameter to the `load_detail` method in `_local_storage_operations.py` to parse special values as strings, adding a new node and function for handling `nan` and `inf` values in the flow configuration, and fixing the handling of invalid JSON values in the visualization.
Main functionality changes:
* <a href="diffhunk://#diff-1a5c2463c2ef997c5203a6b2e77b247d812961b …
> [promptflow][bugfix] Fix "Without Import Data" error in run visualize page due to invalid JSON value

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/azure/_utils/gerneral.py
> [SDK/CLI] Handle user name for non-msft tenant

- src/promptflow/promptflow/batch/_base_executor_proxy.py
- src/promptflow/promptflow/batch/_csharp_executor_proxy.py
- src/promptflow/tests/executor/e2etests/test_csharp_executor_proxy.py
- src/promptflow/tests/executor/mock_execution_server.py
- Add `_is_executor_active()` to check if the executor service is active. If the executor terminates due to some validation errors, the health check can exit early without repetition.
- Each executor proxy is responsible for deleting its own init error file, rather than relying on the `ensure_executor_startup` function to do so.
> [Improvement][Executor] Exit health check loop if executor service is exited

- .cspell.json
- src/promptflow/promptflow/_utils/load_data.py
- src/promptflow/promptflow/batch/_batch_inputs_processor.py
- src/promptflow/tests/executor/unittests/batch/test_batch_inputs_processor.py
- src/promptflow/tests/sdk_cli_test/unittests/test_utils.py
When load data for batch run, we will load all the data of file in memory (do truncation after file loaded) even if max_rows_count is set.
This PR pass the max_rows_count to the file loader to speed up loading.
> [Internal] When load data for batch run, only read first max_rows_count of  rows.

- src/promptflow/promptflow/executor/_tool_resolver.py
- src/promptflow/tests/executor/e2etests/test_executor_validation.py
- src/promptflow/tests/test_configs/wrong_flows/flow_llm_with_wrong_conn/flow.dag.yaml
- src/promptflow/tests/test_configs/wrong_flows/flow_llm_with_wrong_conn/wrong_llm.jinja2
Add validation for wrong connection type for LLM node.
This pull request includes changes related to testing and validation of connections in the `promptflow` codebase. The most important changes include adding a new test case to validate the behavior when a tool load fails due to an invalid connection type, and adding a check to validate the connection type of a node in the `_resolve_llm_node` method.
Testing and validation changes:
* `src/promptflow/tests/executor/e2etests/test_executor_validation.py`: Added a new test case to validate the behavior when a tool load fails due to an invalid connection type. (test_executor_validation.py)
* `src/promptflow/promptflow/executor/_tool_resolver.py`: Added a check to validate the connection type of a node in the `_resolve_llm_node` method. …
> [Bugfix] Add validation for wrong connection type for LLM node.

- src/promptflow/promptflow/_cli/_pf/_run.py
pf run create: add more details for --data and --flow when used with --file parameter.
> pf run create: add more details for --data and --flow when used with --file parameter.

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_cli/_utils.py
- src/promptflow/tests/sdk_cli_test/unittests/test_utils.py
We use `tabulate` to print pandas DataFrame pretty, it requires the column width to be positive. However, in edge case (long column under narrow terminal window), the column width can be negative. This PR targets to fix this by adding a simple `max(1, <width>` to guarantee the postive value, so that users will not run into `ValueError`.
> [promptflow][bugfix] Fix `ValueError: invalid width -1` in `show-details` edge case

- scripts/building/check_enforcer.py
As Azure test CI [sdk-cli-azure-test](https://github.com/microsoft/promptflow/actions/workflows/sdk-cli-azure-test.yml) back to normal, this PR targets to revert the check enforcer changes to make it required again.
> [promptflow][fundamental] Revert to make Azure test CI required again

- src/promptflow/promptflow/_utils/utils.py
- src/promptflow/promptflow/executor/_async_nodes_scheduler.py
- src/promptflow/tests/executor/e2etests/test_executor_happypath.py
- src/promptflow/tests/test_configs/flows/async_tools_with_sync_tools/flow.dag.yaml
Periodically show stack of long running async tasks.
Sample long running message:
```
2024-01-07 19:23:04 +0800   38892 execution          WARNING  sync_passthrough1 in line 0 has been running for 30 seconds, stacktrace of thread 19416:
File "D:\Projects\GitHub\promptflow\src\promptflow\tests\test_configs\flows\async_tools_with_sync_tools\sync_passthrough.py", line 11, in passthrough_str_and_wait_sync
time.sleep(1)
2024-01-07 19:23:04 +0800   38892 execution.flow     WARNING  Task async_passthrough1 has been running for 30 seconds, stacktrace:
File "D:\Projects\GitHub\promptflow\src\promptflow\tests\test_configs\flows\async_tools_with_sync_tools\async_passthrough.py", line 12, in passthrough_str_and_wait
await asyncio.sleep(1)
File …
```
> [Executor] Show long running message for async tool

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_cli/_pf/_init_entry_generators.py
- src/promptflow/promptflow/_cli/_pf/_tool.py
- src/promptflow/promptflow/_cli/data/package_tool/README.md.jinja2
- src/promptflow/promptflow/_cli/data/package_tool/setup.py.jinja2
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
1. Fix invalid tool code generated when initializing the script tool with
2. Fix typo in readme
> [Tool] Fix invalid tool code generated when initializing the script tool with icon

- src/promptflow/promptflow/azure/operations/_arm_connection_operations.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_arm_connection_build.py
Note: this change only effect rest dict returned, the extra 'resource_id' will be removed when converting to sdk connection eneities.
> Add resource id in rest connection object

- src/promptflow/promptflow/_internal/__init__.py
- src/promptflow/promptflow/_utils/multimedia_format_converter.py
- src/promptflow/tests/executor/unittests/_utils/test_multimedia_format_converter.py
Add new util class to convert image url to path and vice versa.
Runtime will need it for universal link in async flow test.
When use this util class, invoker needs to pass in yaml file path, which could make sure contract version is a concept invisible for external.
Introduce `AbstractMultimediaFormatConverter` for contract specific logic.
Expect to inherit it for each future contract.
Please help about thinking a better name than `MultimediaFormatConverter20231201`
New util method addition:
* [`src/promptflow/promptflow/_utils/multimedia_format_converter.py`](diffhunk://#diff-b0656d341f321e5e03d58a69d01e23e98c0f51fa5503a8b99471babc77e70b91R1-R130): Added the `multimedia_format_converter.py` module with classes for converting multimedia expressions between path and URL formats.
> Add util method to convert image url to path and vice versa.

- src/promptflow/tests/sdk_cli_azure_test/conftest.py
- src/promptflow/tests/test_configs/recordings/test_flow_operations_TestFlow_test_list_flows.yaml
Pytest fixture `mock_get_user_identity_info` should use existing `user_object_id` and `tenant_id` to use real values during record, otherwise it will always be sanitized values.
> [promptflow][bugfix] Fix fixture `mock_get_user_identity_info` to use real ids during record mode

- src/promptflow/promptflow/_sdk/_serving/app.py
- src/promptflow/promptflow/contracts/flow.py
- src/promptflow/tests/executor/unittests/contracts/test_flow.py
- src/promptflow/tests/sdk_cli_test/conftest.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_serve.py
Support env variables in yaml file for local serving.
priority for serving:
environment variables passed in kwargs > env in current running environment >environments defined in flow.dag.yaml
there will be no environment variables passed in kwargs for online serving
online serving allow overriding environment variables via container environment variables, which should be contained in os.environ.
environment variables defined in flow.dag.yaml is the default value, if there's no override value provided, the default value will be used.
> [CLI] Support env variables in yaml file for serving.

- src/promptflow/tests/sdk_cli_azure_test/conftest.py
`pytest_mock.MockerFixture` is a function scope fixture, this will lead to test error in live test: [sdk-cli-azure-test](https://github.com/microsoft/promptflow/actions/runs/7561447187/job/20589766200#step:12:541). Replace it with `unitest.mock.patch`, so that it can adjust dynamic fixture scope.
> [promptflow][bugfix] Use `unittest.mock.patch` instead of `MockerFixture`

- src/promptflow/tests/sdk_cli_azure_test/unittests/test_flow_operations.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_utils.py
As our replay tests do not expect real credential/token, we mocked function `FlowServiceCaller._get_user_identity_info`. We detect a regression recently in live test because the regression happens inside the function we mocked, so our replay test cannot cover. This PR targets to add a UT (with some mocks) for better coverage.
> [promptflow][test] Add a UT for `get_user_identity_info`

- src/promptflow/promptflow/executor/_async_nodes_scheduler.py
- src/promptflow/tests/executor/e2etests/test_async.py
Use asyncio.semaphore to support concurrency control.
When node_concurrency is set to 2:
sync_passthrough1 and async_passthrough1 can run concurrently:
When node_concurrency is set to 1:
Only one of sync_passthrough1 and async_passthrough1 can at the same time:
> [Executor] Support node_concurrency when running an async flow

- src/promptflow/promptflow/executor/_line_execution_process_pool.py
- src/promptflow/tests/executor/unittests/processpool/test_line_execution_process_pool.py
Add environment variable 'PF_BATCH_METHOD' to set the multiprocessing start method.
1. If set and valid, use the user set.
2. If set but invalid, use the system default.
3. If not set, use the system default.
> [PromptFlow][Process Pool] Add environment variable 'PF_BATCH_METHOD' to set the multiprocessing start method.

- src/promptflow/promptflow/executor/_async_nodes_scheduler.py
Remove loop parameter in semaphore to avoid TypeError: As of 3.10, the loop parameter was removed from Semaphore() since it is no longer necessary
> [Bugfix] Remove loop parameter in semaphore

- src/promptflow/promptflow/_core/tracer.py
- src/promptflow/tests/executor/unittests/_core/test_tracer.py
- src/promptflow/tests/sdk_cli_test/recording_utilities/mock_tool.py
Currently, when a function is wrapped with `trace()`, the function will set an attribute `__wrapped_function` to itself to note which function has wrapped it.
However, this operation would fail when the function is a built-in function. i.e.
```python
from promptflow import trace
traced_sum = trace(sum)
```
will get this error:
```
AttributeError: 'builtin_function_or_method' object has no attribute '__wrapped_function'
```
This error is because built-in functions in Python are implemented in C and do not have a `__dict__` attribute where we can set arbitrary attributes.
This attribute is not used in our code, and this PR is to remove it.
> Remove unused __wrapped_function

- src/promptflow/promptflow/_core/_errors.py
- src/promptflow/promptflow/_core/tool_meta_generator.py
- src/promptflow/promptflow/_core/tools_manager.py
- src/promptflow/promptflow/executor/_errors.py
- src/promptflow/promptflow/executor/_tool_resolver.py
- src/promptflow/tests/executor/e2etests/test_executor_validation.py
- src/promptflow/tests/executor/unittests/_core/test_tools_manager.py
- src/promptflow/tests/executor/unittests/_utils/test_generate_tool_meta_utils.py
- src/promptflow/tests/executor/unittests/executor/test_tool_resolver.py
Use relative path in gen meta/ load tool error message. Absolute paths convey too much extra info.
Move `InvalidSource` from `executor._errors` to `_core._errors` for circular reference.
> Use relative path in gen meta/ load tool error message.

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_cli/_pf/_connection.py
- src/promptflow/promptflow/_cli/_pf/_flow.py
- src/promptflow/promptflow/_cli/_pf/_run.py
- src/promptflow/promptflow/_cli/_utils.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
This pull request primarily focuses on improving the user experience when deleting connections and runs in the `promptflow` CLI by introducing an option to skip confirmation prompts. The changes also include some minor refactoring of the codebase.
User Experience Improvements:
* [`src/promptflow/promptflow/_cli/_pf/_connection.py`](diffhunk://#diff-cfa3edaa5d4e3792cdc8df6feab431705cc857b143270b1291f9d8a2cc98b695L9-R15): Added `add_param_yes` to the import statement, and modified `add_connection_delete` to include `add_param_yes` in the `add_params` list. This allows users to skip the confirmation prompt when deleting a connection. [[1]](diffhunk://#diff-cfa3edaa5d4e3792cdc8df6feab431705cc857b143270b1291f9d8a2cc98b695L9-R15) [[2]](diffhunk://#diff-cfa3edaa5d4e3792cdc8df6feab431705cc857b1432 …
> [Cli]Add option to skip confirm dialog

- src/promptflow/promptflow/_cli/_pf/_flow.py
- src/promptflow/promptflow/_sdk/_utils.py
- src/promptflow/promptflow/_sdk/operations/_flow_operations.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
For `pf flow test`, this _internal_ PR targets to support suppress parameter `--detail` to specify additional command artifact output path:
- test flow: `pf flow test --flow . --detail </path/to/somewhere>`
- test a single node in the flow: `pf flow test --flow . --node fetch_text_content_from_url --inputs inputs.url=https://www.microsoft.com/en-us/d/xbox-wireless-controller-stellar-shift-special-edition/94fbjc7h0h6h --detail </path/to/somewhere>`
Prompt flow will **ALSO** persist command artifact (detail and output JSON, plus log) under specified path.
> [promptflow][internal] Support configurable additional flow test output folder

- src/promptflow/promptflow/_utils/multimedia_utils.py
Fix bug when raising exception. When loading multimedia data, we catch all exceptions and raise a `LoadMultimediaDataError`, and we set the target of the exception to the target of original exception, but if the original exception is a python built-in exception, it doesn't have a property target, which may cause problem. We should directly set the target to `ErrorTarget.EXECUTOR`.
> [BugFix][Executor] Fix bug when raising exception in load_multimedia_data

- src/promptflow/promptflow/executor/_script_executor.py
The error occurred when run `pf run show-details -n xxx`, since the inputs of eager flow run info didn't contain `line_number`, which is because we removed the `line_number` before writing it to run info, so we should remove it after creating run info.
> [Bugfix][Executor] Include line_number in run_info.inputs for eager flow

- src/promptflow/promptflow/_sdk/_orm/session.py
This PR reverts #1853 to silence warning for those users who still use SQLAlchemy<2.0.0.
> [promptflow] Revert silence warning for SQLAlchemy and update comment

- .github/workflows/check_enforcer.yml
- scripts/building/check_enforcer.py
- scripts/check_enforcer/check_enforcer.py
Check enforcer should check against merge_base
move enforcer to new folder, and avoid trigger too many code for check_enforcer changes.
> [fundamental] Check enforcer should check against merge_base

- src/promptflow/promptflow/executor/_errors.py
- src/promptflow/promptflow/executor/_line_execution_process_pool.py
- src/promptflow/promptflow/executor/_process_manager.py
- src/promptflow/tests/executor/unittests/processpool/test_line_execution_process_pool.py
- src/promptflow/tests/sdk_cli_test/conftest.py
**Problem**
Currently, in fork mode, when spawn process raises an exception, the process will hang and not raise the exception to main process. So we need to solve the problem.
**Solution**
1. In fork mode, the spawn process is the bridge between the main and fork processes. If the spawned process is no longer running, exit the main process.
2. Add try-catch in the spawned process, if an exception occurred, log the error message.
3. In the Monitor thread, if not get the process info within the 60s, raise an exception.
> [PromptFlow][ProcessPool] Solve spawned fork process manager hangs for a long time when parameters are passed incorrectly.

- docs/how-to-guides/faq.md
The PR  [[PromptFlow][Executor][Internal] Refine process pool.](https://github.com/microsoft/promptflow/pull/1582) modify the default worker count to 4, this PR modify related documents.
> [PromptFlow][Document] Modify default worker count to 4.

- src/promptflow/promptflow/_core/tracer.py
- src/promptflow/setup.py
- src/promptflow/tests/executor/unittests/_core/test_tracer.py
This PR introduces OpenTelemetry support for the trace decorator in PromptFlow. The `trace` decorator, which is applied to tool and openai APIs, now generates OpenTelemetry spans containing execution information. This enhancement allows for detailed tracking of function execution within the PromptFlow scope.
Key changes include:
- Generation of a span before the execution of the decorated function.
- Setting span attributes with execution information such as input and TraceType.
- Addition of the function's result as an output attribute to the span.
A test has been added to validate these changes.
> Add OpenTelemetry Support for Trace Decorator in PromptFlow

- src/promptflow/promptflow/_core/tracer.py
This PR fixes a bug in the `tracer.py` file where the `get_node_name_from_context` function was being assigned as an object instead of being called to get its return value. This was causing unexpected exceptions in subsequent execution. The fix ensures that the function is called correctly, preventing these exceptions.
> Call `get_node_name_from_context` function instead of assigning it as an object in tracer.py

- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/promptflow/_sdk/schemas/_flow.py
- src/promptflow/promptflow/azure/_entities/_flow.py
- src/promptflow/promptflow/batch/_base_executor_proxy.py
- src/promptflow/promptflow/batch/_batch_engine.py
- src/promptflow/promptflow/batch/_csharp_executor_proxy.py
This pull request primarily involves changes that enhance language support and improve the handling of flow schemas in the `promptflow` package. The changes include the introduction of validation and default values for the `language` field in flow schemas, modifications to the handling of eager flows in the batch engine, and the addition of methods to fetch flow metadata and input definitions.
Language Support and Flow Schema Changes:
* [`src/promptflow/promptflow/_sdk/schemas/_flow.py`](diffhunk://#diff-84af29d72d79c61d55daa91de77a03235646967bcaa7c3299f33adcead97bc53R4-R8): The `language` field in the `BaseFlowSchema` class now has a default value and validation to ensure it's either Python or CSharp. In the `EagerFlowSchema` class, the `path` field is no longer required, and a …
> feat: support csharp eager mode batch run

- src/promptflow/promptflow/_core/operation_context.py
- src/promptflow/promptflow/_core/tracer.py
- src/promptflow/promptflow/_trace/_start_trace.py
- src/promptflow/promptflow/executor/flow_executor.py
Refine the logic to add otel common attributes and add line_run_id in it.
This pull request primarily focuses on enhancing the OpenTelemetry (OTel) attributes handling in the `promptflow` package. The main changes include the addition of OTel attributes handling methods in the `OperationContext` class, the removal of the `TRACE_SESSION_ID_OP_CTX_NAME` constant from the `tracer.py` file, and the modification of the `enrich_span_with_trace` function to use the new OTel attributes methods. Furthermore, the `SpanAttributeFieldName.SESSION_ID` attribute is now added to the operation context in the `_provision_session` function, and a new attribute `line_run_id` is added in the `_update_operation_context` function when the run mode is `Test`.
Enhancements to OpenTelemetry attributes handling:
* …
> [Executor][Internal] Add line run id to otel span

- src/promptflow/promptflow/_core/openai_injector.py
- src/promptflow/promptflow/_core/operation_context.py
- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/e2etests/test_eager_flow.py
- src/promptflow/tests/executor/e2etests/test_telemetry.py
- src/promptflow/tests/executor/unittests/_core/test_api_injector.py
- src/promptflow/tests/executor/unittests/_core/test_operation_context.py
- src/promptflow/tests/test_configs/eager_flows/flow_with_operation_context/flow_with_context.py
Only include required items in telemetry headers by fetching keys from tracking_keys
This pull request primarily refactors how telemetry data is tracked and validated in the `OperationContext` and `openai_injector` classes of the `promptflow` package. The changes ensure that only primitive data types are included in the telemetry headers, and add the ability to customize which keys are tracked for telemetry. The changes also include updates to the corresponding unit tests.
Key Changes:
**Refactoring of Telemetry Data Handling:**
* [`src/promptflow/promptflow/_core/openai_injector.py`](diffhunk://#diff-5aa1742dea161ecc0d7aab4d778e7ae50dd9c935fd76e1b8f6599cad20473fd8L49-R62): The `get_aoai_telemetry_headers` method now retrieves tracking info from `OperationContext` instead of the context …
> [Executor][Internal]Put only required items in aoai telemetry headers

- src/promptflow/promptflow/_core/openai_injector.py
- src/promptflow/promptflow/_core/tracer.py
This pull request primarily introduces changes to the `src/promptflow/promptflow/_core/tracer.py` file. The main focus of the changes is to enhance the tracing mechanism by adding a `TokenCollector` class for collecting OpenAI tokens associated with spans, and integrating it into the existing tracing flow. The changes also include a minor import modification for the OpenTelemetry library.
Main Changes:
* [`src/promptflow/promptflow/_core/tracer.py`](diffhunk://#diff-8f8c2ae53e5ffd37a14e8a899119fbb2742486db8faab6df3fcf506e1b720ad8R159-R198): Introduced a new class `TokenCollector` to collect OpenAI tokens associated with spans. The class provides methods to collect tokens, merge tokens for parent spans, and retrieve tokens for a given span id.
* …
> [Executor] Update openai tokens to trace

- examples/gen_test_data/gen_test_data/common.py
- examples/gen_test_data/requirements.txt
- examples/gen_test_data/requirements_cloud.txt
> Fix version and invalid file path

- examples/gen_test_data/gen_test_data/generate_test_data_flow/flow.dag.yaml
- examples/gen_test_data/gen_test_data/generate_test_data_flow/generate_debug_info.py
- examples/gen_test_data/gen_test_data/generate_test_data_flow/validate_question.py
- examples/gen_test_data/gen_test_data/generate_test_data_flow/validate_suggested_answer.py
- examples/gen_test_data/gen_test_data/generate_test_data_flow/validate_text_chunk.py
https://ml.azure.com/prompts/flow/3e123da1-f9a5-4c91-9234-8d9ffbb39ff5/cfe95e18-49b1-46f5-bb46-8cc6969218ac/details?wsid=/subscriptions/96aede12-2f73-41cb-b983-6d11a904839b/resourcegroups/promptflow/providers/Microsoft.MachineLearningServices/workspaces/promptflow-eastus&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
> fix flow run on portal

- src/promptflow/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/e2etests/test_executor_validation.py
Only assign flow run info's input after validation and loading image.
It's a better way to handle inputs, because 
1. A wrong input is not yet the flow run's input from concept.
2. Assign wrong input may introduce bug for storage's persisting. We should not expect storage could handle all abnormal case rightly.
> Only assign inputs after validation and loading image.

- src/promptflow/promptflow/_sdk/_submitter/experiment_orchestrator.py
- src/promptflow/promptflow/_sdk/_submitter/test_submitter.py
- src/promptflow/promptflow/_sdk/entities/_trace.py
- src/promptflow/promptflow/_sdk/operations/_experiment_operations.py
- src/promptflow/promptflow/_sdk/operations/_flow_operations.py
- src/promptflow/promptflow/_sdk/operations/_trace_operations.py
- src/promptflow/promptflow/_trace/_start_trace.py
- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_telemetry.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_experiment.py
- Fix line run evaluations calculation.
- Call start_trace for flow test.
Example for experiment test:
> [SDK][Internal] Call `start_trace()` for flow test when internal enabled

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_sdk/_serving/extension/azureml_extension.py
there are multiple internal implementation inside ManagedIdentityCredential, not all of the implementations handle the UAI with AZURE_CLIENT_ID, we need to pass it as client_id when initialize the ManagedIdentityCredential
> fix uai get token bug

- examples/gen_test_data/gen_test_data/common.py
rename logger name of node inputs override to make log line align with others
> rename logger name of node inputs override

- src/promptflow/promptflow/_core/tracer.py
- src/promptflow/tests/executor/e2etests/test_batch_engine.py
- src/promptflow/tests/executor/unittests/_core/test_tracer.py
Currently there are following warnings when directly call some function with @trace
```
WARNING:root:Try to push trace but no active tracer in current context.
WARNING:opentelemetry.attributes:Invalid type NoneType for attribute 'node_name' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequen
WARNING:root:Try to push trace but no active tracer in current context.
WARNING:opentelemetry.attributes:Invalid type NoneType for attribute 'node_name' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
```
This pull request for `src/promptflow/promptflow/_core/tracer.py` includes changes that simplify the code and improve error handling. The most significant changes include removing unnecessary logging warnings and exception raising …
> [Executor][Internal] Adjust legacy tracer logic to avoid warnings when directly uses trace

- src/promptflow/promptflow/_constants.py
- src/promptflow/promptflow/_sdk/_orm/trace.py
- src/promptflow/promptflow/_sdk/_service/apis/span.py
- src/promptflow/promptflow/_sdk/_service/templates/ui_traces.html
- src/promptflow/promptflow/_sdk/entities/_trace.py
- src/promptflow/promptflow/_sdk/operations/_trace_operations.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_experiment.py
**Bug fix**
Make sure line runs covering all traces.
**Compatible with standard trace**
Use `get()` to avoid `KeyError` when handle standard trace without `session_id` and `span_type` in attributes.
**Copy button**
Add a copy button at the very top of the trace UI page, so that we can easily copy the JSON to UX demo page for rendering.
**Order by start time**
List traces order by `start_time`.
> [promptflow][internal] Fix standard OpenTelemetry traces collection and line run list bug

- src/promptflow/promptflow/_sdk/entities/_trace.py
- src/promptflow/promptflow/_sdk/operations/_trace_operations.py
In many scenarios (line is still executing, terminated, or even killed for some reasons), there will be no main root span, to avoid exception, we should ignore this line run.
> [promptflow][internal] BugFix: ignore line run when main root span is absent

- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/promptflow/storage/__init__.py
- src/promptflow/promptflow/storage/_run_storage.py
- src/promptflow/tests/executor/unittests/storage/test_local_storage_operations.py
1. In _local_storage_operations.py, maintain dicts of node run and flow run info to quickly get run info for certain line number. Split load_details into two functions to avoid repetition of calls.
2. In _run_storage, add class AbstractBatchRunStorage which inherits AbstractRunStorage. It has unique load functions.
3. Add test case for load functions.
> Add load function for flow run and node run

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_cli/_utils.py
- src/promptflow/promptflow/_constants.py
- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_utils.py
- [SDK/CLI] Support configuring environment variable to directly use `AzureCliCredential` for `pfazure` commands.
```dotenv
USE_AZURE_CLI_CREDENTIAL=true
```
> [SDK/CLI] Support user to configure AzureCliCredential for pfazure commands

- .github/workflows/build_msi_installer.yml
- src/promptflow/promptflow/_sdk/_service/entry.py
- src/promptflow/promptflow/_sdk/_service/utils/utils.py
> Fix MSI installation scripts

- src/promptflow/promptflow/_sdk/_configuration.py
- src/promptflow/promptflow/_sdk/_utils.py
- src/promptflow/tests/sdk_cli_test/unittests/test_utils.py
Due to the inability to fix the name of the first network card, for example, for laptops and Mac mini, their names are different, so change from obtaining the first network card MAC address to obtaining all MAC addresses.
> improve get_mac_address

- src/promptflow/promptflow/_utils/thread_utils.py
- src/promptflow/promptflow/executor/_async_nodes_scheduler.py
- src/promptflow/tests/executor/e2etests/test_logs.py
- src/promptflow/tests/executor/unittests/_utils/test_thread_utils.py
Add subclass for `threading.Thread`, which could copy context vars by default.
Using this subclass to fix async execution's log missing issue.
We are using `FileHandlerConcurrentWrapper` to write log content to specific logger file.
Which will retrieve `FileHandler` by context var.
If don't copy contextvars, the log content will not be written to file.
> Create util method to create new thread with context vars.

- src/promptflow/promptflow/batch/_batch_engine.py
Add input parameters `resume_from_run_storage` and `resume_from_run_output_dir` to `BatchEngine.run` method.
It is the contract between SDK/Runtime and batch engine to support resume from feature.
> Add resume from contract to batch engine

- examples/gen_test_data/config.ini.example
- examples/gen_test_data/gen_test_data/common.py
- examples/gen_test_data/gen_test_data/run.py
In local mode, we first attempt to use the configured `document_nodes_file` if it's valid, otherwise, we fall back to `documents_folder`. In cloud mode, `document_nodes_file` is used if configured, without any validity checks because we cannot check if it is a data asset. For cloud mode, both local files and data assets can be used.
**Local Tests:**
1. happy path
- skip split 
- has split: 
`documents_folder = "..\..\docs\reference\tools-reference"`
2. invalid file path and folder path
**Cloud Tests:**
1. happy path (local and asset)
- local path
skip split:  https://ml.azure.com/runs/tough_guava_3znwhjb9sc?wsid=/subscriptions/96aede12-2f73-41cb-b983-6d11a904839b/resourcegroups/promptflow/workspaces/yaopfeus&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
has split: …
> Support data asset input

- .github/workflows/build_msi_installer.yml
- src/promptflow/promptflow/_cli/_pf/_upgrade.py
- src/promptflow/promptflow/_utils/version_hint_utils.py
- Update promptflow package version when set msi private version
- get latest json version when msi pf upgrade
https://github.com/microsoft/promptflow/actions/runs/7957234441
> Update msi package process and get latest json version when msi pf upgrade

- src/promptflow/promptflow/_core/run_tracker.py
- src/promptflow/promptflow/_core/tracer.py
- src/promptflow/promptflow/_utils/multimedia_utils.py
- src/promptflow/promptflow/_utils/utils.py
when execute node of assistant, there would a warning message.  This PR is to fix this.
2024-02-20 16:18:49 +0800    4764 execution.flow     WARNING  Input 'assistant_definition' of assistant is not json serializable, use str to store it.
> Fixing the AssistantDefinition not serializable warnings when ensure input serializable

- src/promptflow/MANIFEST.in
- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/_service/apis/line_run.py
- src/promptflow/promptflow/_sdk/entities/_trace.py
- src/promptflow/tests/sdk_pfs_test/e2etests/test_trace.py
- src/promptflow/tests/sdk_pfs_test/utils.py
There is a schema bug for `cumulative_token_count`, it should be an optional dictionary, instead of an optional string.
This PR targets to fix this, so that we can have correct response, and it will be correctly rendered in trace UI; also try to add an end-to-end test to guard this behavior.
This PR also fixes missing update for MANIFEST in #2035 , which leads to missing files when build.
> [promptflow][internal] Fix `cumulative_token_count` schema error

- src/promptflow/promptflow/_sdk/entities/_trace.py
- src/promptflow/tests/sdk_cli_test/unittests/test_trace.py
We have observed scenario that some 3p traces do not have field `attributes`, which will lead to a `KeyError`.
This PR targets to fix that with using `dict.get`, plus adding a unit test to guard this.
> [promptflow][internal] Fix traces missing attributes collection bug

- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_run_operations.py
We have observed a flaky live test `test_get_details_against_partial_completed_run` that results from a known executor/runtime bug when in Azure. This PR targets to leverage `xfail` to handle this flaky test.
**Reference**: <https://pytest.org/en/7.4.x/how-to/skipping.html#xfail-mark-test-functions-as-expected-to-fail>
> [promptflow][bugfix] XFail for flaky test `test_get_details_against_partial_completed_run`

- src/promptflow/promptflow/_core/operation_context.py
Experiment run may set 'reference.batch_run_id' to None, filter it out when get otel attributes to avoid following logic exception.
> [Internal] Filter None value out when get otel attributes

- src/promptflow-tools/promptflow/tools/aoai.py
- src/promptflow-tools/promptflow/tools/aoai_gpt4v.py
- src/promptflow-tools/promptflow/tools/openai.py
- src/promptflow-tools/promptflow/tools/openai_gpt4v.py
- src/promptflow-tools/tests/test_aoai.py
- src/promptflow-tools/tests/test_aoai_gptv.py
- src/promptflow-tools/tests/test_openai.py
- src/promptflow-tools/tests/test_openai_gpt4v.py
openai by default will retry twice, but there is no way to get retry status log by its sync api. 
If use async openai api, we can get the log, but the log level is info, we only save warning level log for batch run considering cost.
A more appropriate way is to disable openai builtin retry by setting `max_retries=0`. We have custom retry mechanism which can provide good debuggability experience.
> disable openai built-in retry mechanism for better debuggability and real-time status updates

- src/promptflow-tools/promptflow/tools/open_model_llm.py
Legacy error name 'OpenSourceLLMOnlineEndpointError', should be 'OpenModelLLMOnlineEndpointError'
> [Bugfix] fix naming error of legacy 'OpenSourceLLMOnlineEndpointError'

- src/promptflow-tools/promptflow/tools/aoai.py
- src/promptflow-tools/promptflow/tools/common.py
- src/promptflow-tools/tests/test_handle_openai_error.py
Currently the retry-after interval for openai retry error is multiplied by (2 ** i):
1. error without retry-after header: 8 * (2 ** i);
2. error with retry-after header: float(retry_after_in_header) * (2 ** i)
This calculation will cause the retry-after very large when the i (retry_count) is large, e.g.: 608s
This will result in:
1. the job running for a long time, and most of the time are waiting interval, make the resource been wasted.
2. Some lines will failed with timeout because of the long retry-after interval.
Thus, we want to refine the retry-after interval for openai retry error like below:
1. error without retry-after header: minbackoffinsec + (2**i - 1). If this value is larger than 60s, then use 60s instead.
2. error with retry-after header: float(retry_after_in_header). Just …
> [Internal] Refine the retry-after interval for openai retry error

- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_run.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_test.py
- src/promptflow/tests/test_configs/eager_flows/environment_variables/env_var.py
- src/promptflow/tests/test_configs/eager_flows/environment_variables/flow.dag.yaml
- src/promptflow/tests/test_configs/eager_flows/environment_variables_connection/evc.py
- src/promptflow/tests/test_configs/eager_flows/environment_variables_connection/flow.dag.yaml
This pull request primarily focuses on the refactoring of test cases and related configurations in the `src/promptflow/tests` directory. The changes include renaming of functions and files, modifying the way flow dags are removed, and updating the module names in the `clear_module_cache` function calls.
Test case refactoring:
* [`src/promptflow/tests/sdk_cli_test/e2etests/test_flow_run.py`](diffhunk://#diff-94a59a05643476869fa3c6bc45466f1582944a935488075e2e63b6a6a196958fL1297-R1298): In the `test_get_incomplete_run` function, the removal of the flow dag has been changed from removing the entire directory to unlinking the specific `flow.dag.yaml` file.
* …
> [Tests] Fix environment related eager flow tests & test_get_incomplete_run

- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
Remove batch run timeout tests
> [CLI] remove batch run timeout tests.

- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/entities/_connection.py
- src/promptflow/promptflow/_sdk/schemas/_connection.py
- src/promptflow/promptflow/_trace/_start_trace.py
- src/promptflow/promptflow/azure/operations/_arm_connection_operations.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_arm_connection_build.py
- src/promptflow/tests/sdk_cli_test/unittests/test_connection.py
- src/promptflow/tests/test_configs/connections/serverless_connection.yaml
> [SDK][Connection] Support serverless connection type

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_sdk/entities/__init__.py
- src/promptflow/promptflow/azure/operations/_arm_connection_operations.py
- src/promptflow/promptflow/connections/__init__.py
- src/promptflow/setup.py
> [SDK] Add serverless connection to init & fix vulnerable package

- src/promptflow/promptflow/executor/flow_executor.py
Currently flow level trace is always "Success" since we wrapped it in wrong place.
Update such code to make sure the error is correctly caught in the span.
This pull request includes significant changes to the `FlowExecutor` class in the `src/promptflow/promptflow/executor/flow_executor.py` file. The primary changes involve refactoring the `_exec_with_trace` method and its usages throughout the class. The method has been split into two separate methods: `_exec_inner_with_trace` and `_exec_inner`. The functions `_exec`, `exec_line`, `_exec_in_thread`, and `exec` have been updated to use these new methods. The changes aim to improve the readability and maintainability of the code.
Updates to method usages:
* The `exec` method now calls `_exec` instead of `_exec_with_trace`.
* The …
> [Executor][Bugfix] Adjust flow traces logic to make sure error is correctly raised

- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/tests/executor/unittests/storage/test_local_storage_operations.py
Load image to memory in 1load_flow_run_info` and `load_node_run_info_for_line` API of `LocalStorageOperations`.
So that the resume feature can work for image scenario.
> Load image in local storage

- src/promptflow/promptflow/executor/_tool_resolver.py
- src/promptflow/tests/executor/e2etests/test_executor_happypath.py
- src/promptflow/tests/executor/e2etests/test_executor_validation.py
Enable serverless connection in scenario that related tool is not ready.
We achieve this by converting it to an openai connection, which will go to the openai connection code path.
Note that we also changed the logic about provider resolving that we always use the provider from the connection instead of the user provided one to make sure the provider is consistent with the connection.
This pull request includes significant changes to the `src/promptflow/promptflow/executor/_tool_resolver.py` file, which improve the handling of connections and providers in the `_resolve_llm_node` method and related methods. The changes also include updates to the corresponding test cases in `src/promptflow/tests/executor/e2etests/test_executor_happypath.py` and …
> [Executor][Feature]Enable serverless connection by converting to openai connection

- src/promptflow/promptflow/_utils/feature_utils.py
Add resume batch run feature to feaure list.
> Add resume batch run feature

- src/promptflow/promptflow/_cli/_utils.py
- src/promptflow/promptflow/_constants.py
- src/promptflow/promptflow/_sdk/_configuration.py
- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/_utils.py
- src/promptflow/promptflow/_sdk/operations/_local_azure_connection_operations.py
- src/promptflow/promptflow/_trace/_start_trace.py
- src/promptflow/tests/sdk_cli_test/unittests/test_trace.py
Support `pf config set trace.provider=azureml://subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.MachineLearningServices/workspaces/<workspace_name>` to configure local to cloud, and will record triad in `resource.attributes`:
If the user has enabled local to cloud feature, plus print an url for the UI link:
> [internal][trace] Support `pf config set trace.provider` and print url for local to cloud

- src/promptflow/promptflow/_sdk/_service/app.py
- src/promptflow/promptflow/_sdk/_submitter/experiment_orchestrator.py
- src/promptflow/promptflow/_sdk/_utils.py
For the process started in detach mode like local pfs, stdout/stderr will be none([doc](https://docs.python.org/2/library/subprocess.html#subprocess.Popen.stdin)).
To avoid exception to stdout/stderr calls in the dependency package, point stdout/stderr to devnull.
> Init sys.stdout and sys.stderr to avoid exception when started in detach mode.

- examples/gen_test_data/gen_test_data/generate_test_data_flow/generate_question_prompt.jinja2
For some text chunks, compare the questions before and after modification. Use the model "gpt-4-1106-preview". Each text chunk run 5 to 10 times continuously to verify the results.
**before question:** `What is the purpose of the condition_output in the given pipeline code?`
**before answer:** `The purpose of the condition_output in the given pipeline code is to selectively return one of two inputs based on a condition that is evaluated at runtime. If the condition evaluates to True, condition_output will return the first input (input_a), otherwise, it will return the second input (input_b). This allows for dynamic control of the data flow within the pipeline, depending on the results of previous tasks or workflow inputs.`
**after question:** `How does the condition_output function decide …
> Tune prompt to avoid question with `in this context/in given code/in table`

- src/promptflow/promptflow/executor/_line_execution_process_pool.py
- src/promptflow/promptflow/executor/_process_manager.py
This pull request primarily focuses on improving the process termination and monitoring in the `promptflow` package. Previously the subprocess always run a dead cycle, and it relies on the call `process.terminate()` to kill the subprocess, it caused that the exporter of `opentelemetry` cannot shutdown properly. in this PR, we send the terminate signal to the subprocess and it will break out of the loop, and we will wait it to be ended in the monitor thread. 
The changes are mainly in two files: `src/promptflow/promptflow/executor/_line_execution_process_pool.py` and `src/promptflow/promptflow/executor/_process_manager.py`. The most significant changes include the introduction of a `TERMINATE_SIGNAL` for process termination, modifications to the …
> [Executor] Line process to wait for otel exporter

- docs/how-to-guides/develop-a-tool/create-and-use-tool-package.md
- src/promptflow/promptflow/_core/tools_manager.py
This pull request includes changes to the `create-and-use-tool-package.md` and `tools_manager.py` files. The `collect_package_tools` failed in python 3.12, that's because in python 3.12 `importlib.metadata.entry_points()` is a tuple-like object, while in python 3.10 and 3.11 it is a dictionary-like object, but they both have a method `select` to filter group from the entry points, so we change to check if there is the attrubute `select`: `hasattr(entry_points, "select")`.
The changes involve updating the method of checking the type of `entry_points` from `isinstance(entry_points, list)` to `hasattr(entry_points, "select")`. This change is likely made to accommodate for different versions of the `importlib.metadata.entry_points()` method, which may return a different type of object …
> Fix bug when collect package tools

- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/_orm/trace.py
- src/promptflow/promptflow/_sdk/entities/_trace.py
- src/promptflow/promptflow/_sdk/operations/_trace_operations.py
- src/promptflow/tests/sdk_pfs_test/e2etests/test_trace.py
- src/promptflow/tests/sdk_pfs_test/utils.py
- Fix empty result when query line runs with eval run name, by separating query run logic
- Limit 1000 for empty query parameter
> [internal][bugfix] Fix empty result when query with eval run name

- src/promptflow/promptflow/_sdk/data/tool.schema.json
Type validation logic enabled by https://github.com/microsoft/promptflow/pull/2041 for extension.
assistant_definition is missing there which failed the assistant sample.
> Add assistant_defintion type into schema for local tool meta gen

- src/promptflow/promptflow/azure/_storage/cosmosdb/summary.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_summary.py
For aggregate node/eager flow/arbitrary script, they don't have line run id/batch run id in span.
And we don't have a way to separate them from each other.
For cosmosDB table, we want to persist them as main flow item in `LineSummary` table.
But don't need to patch them as one item in `evaluations`
For example:
> Persist as main flow in LineSummary when span don't have id (for eager mode/arbitrary script)

- src/promptflow/promptflow/_sdk/_service/apis/collector.py
CosmosDB's init could be time-consuming.
Move this operation to worker thread to avoid making whole request timeout.
We may could further improve it by avoid using one same `_thread_lock` for all clients.
> Write trace to cosmosDB in separate thread to avoid making whole request timeout.

- src/promptflow/tests/_constants.py
- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_run_operations.py
- src/promptflow/tests/sdk_cli_azure_test/recording_utilities/constants.py
- src/promptflow/tests/sdk_cli_azure_test/recording_utilities/utils.py
- src/promptflow/tests/test_configs/recordings/test_run_operations_TestFlowRun_test_run_with_compute_instance_session.yaml
- src/promptflow/tests/test_configs/recordings/test_run_operations_TestFlowRun_test_run_with_compute_instance_session_yml.yaml
When SDK tries to submit run to Azure, the request body may contain a field `computeName`, this need to be sanitized during record/replay - this PR targets to do this and enable related skipped tests.
> [promptflow][bugfix] Sanitize `computeName` in submit request and enable related tests

- src/promptflow/tests/sdk_cli_test/e2etests/test_experiment.py
For `LineRun.evaluations`, it will be a dict for now, update the corresponding test; need to improve coverage on this.
> [promptflow][bugfix] Fix breaking test due to `LineRun.evaluations` contract change

- docs/dev/replay-e2e-test.md
- src/promptflow/tests/sdk_cli_test/conftest.py
- src/promptflow/tests/sdk_cli_test/recording_utilities/__init__.py
- src/promptflow/tests/sdk_cli_test/recording_utilities/record_storage.py
Pydantic model is key items recorded in local recording mode.
By the way, the pipeline is using pydantic > 2  when running tests.
> [Fundamental] stop record and warn to upgrade pydantic in record/replay mode

- src/promptflow/promptflow/_sdk/_service/apis/collector.py
- src/promptflow/promptflow/_sdk/_service/app.py
- src/promptflow/promptflow/azure/_storage/cosmosdb/span.py
- src/promptflow/promptflow/azure/_storage/cosmosdb/summary.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_span.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_summary.py
For portal trace, we use one link to show all flow test's traces from same workspace.
Customer must need some way to filter between themselves and others.
So, we add `created_by` here to enable UI add corresponding feature later.
Example:
> Add created_by info to cosmosDB's trace

- src/promptflow-tools/promptflow/tools/aoai_gpt4v.py
- src/promptflow-tools/tests/test_aoai_gptv.py
Currently, the passed in connection is string, in list_deployment_names use it directly as name parameter.
Extension test:
Portal test:
> [BugFix]Update list_deployment_names, check connection type

- src/promptflow/promptflow/_sdk/_service/apis/collector.py
- src/promptflow/promptflow/azure/_storage/cosmosdb/client.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_cosmosdb.py
Currently, first call to _try_write_trace_to_cosmosdb may take long time. 
In this PR, we init two client in parallel to speed up the init. This will reduce 10s to 20s of the init time.
> [Internal] Init Span/LineSummary client in parallel

- src/promptflow/promptflow/executor/_line_execution_process_pool.py
Meet span missing issue for batch run. Which means:
1. Span exporter doesn't submit request to local PFS at all
2. Span exporter may just submit part of spans for one line in request
3. Span exporter may just submit one line's span but ignore other lines
There is a previous PR to fix same issue: https://github.com/microsoft/promptflow/pull/2103
In this PR, shutdown span processor manually to fix the issue. (Will flush all the waiting spans)
Keep the 10 seconds wait from previous PR to guarantee Exporter could receive response from local PFS.
> Shutdown span processor when end process to guarantee span is exported

- src/promptflow/promptflow/_sdk/_submitter/run_submitter.py
Always cleanup `referenced.batch_run_id` when submit a run, which can avoid mis-inheritance of run lineage.
> [tracing][bugfix] Cleanup `referenced.batch_run_id` when submit run

- src/promptflow/promptflow/_utils/tool_utils.py
- src/promptflow/tests/executor/unittests/_utils/test_generate_tool_meta_utils.py
- src/promptflow/tests/test_configs/eager_flows/flow_with_dataclass_output/flow_with_dataclass.meta.json
- src/promptflow/tests/test_configs/eager_flows/flow_with_dataclass_output/flow_with_dataclass.py
If the output of eager flow is a dataclass, we want to show the properties of the dataclass in the flow meta.
The definition of dataclass:
```
@dataclass
class Data:
text: str
models: list
```
Generated flow meta:
```
{
"function": "my_flow",
"entry": "flow_with_dataclass:my_flow",
"inputs": {
"text": {
"type": "string"
},
"models": {
"type": "list"
}
},
"outputs": {
"text": {
"type": "string"
},
"models": {
"type": "list"
}
},
"source": "flow_with_dataclass.py"
}
```
> Include dataclass output in flow meta

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/entities/_experiment.py
- src/promptflow/promptflow/_sdk/entities/_run.py
- src/promptflow/promptflow/azure/operations/_run_operations.py
This pull request primarily focuses on modifying the way the home directory is accessed in the `promptflow` package. Instead of directly using `PROMPT_FLOW_DIR_NAME`, the code now uses `HOME_PROMPT_FLOW_DIR`. This change has been applied across multiple files and methods to maintain consistency and improve the code's readability and maintainability.
Changes to `src/promptflow/promptflow/_sdk/_constants.py`:
* Added a comment to discourage the direct use of `PROMPT_FLOW_DIR_NAME` for the home directory and recommended the use of `HOME_PROMPT_FLOW_DIR` instead.
Changes to `src/promptflow/promptflow/_sdk/entities/_experiment.py`:
* Replaced `PROMPT_FLOW_DIR_NAME` with `HOME_PROMPT_FLOW_DIR` in the import statement.
* Modified the `_output_dir` attribute …
> fix: runs and logs won't respect PF_HOME_DIRECTORY

- src/promptflow/promptflow/_core/operation_context.py
- src/promptflow/promptflow/executor/flow_executor.py
Currently call a flow in a flow node will fail due to wrongly handled operation context, in this PR, we fix it by copy the original context and recover.
Issue: https://github.com/microsoft/promptflow/issues/2237
This pull request primarily focuses on refactoring the handling of operation contexts in the `promptflow` package. The most significant changes include the addition of a `copy` method to the `OperationContext` class, the introduction of a `set_instance` class method to the same class, and changes to the `exec_line_async` and `_update_operation_context` methods in the `FlowExecutor` class to utilize these new methods. 
Here is a breakdown of the key changes:
Changes to `OperationContext` class in `src/promptflow/promptflow/_core/operation_context.py`:
* A `copy` method has been …
> [Bugfix] Fix the bug that call flow in flow function will fail

- docs/how-to-guides/manage-runs.md
Existing docs give wrong command line at this url; user expects to get tabular output, but command shown gives json output: https://microsoft.github.io/promptflow/how-to-guides/manage-runs.html#show-run-metrics
ISSUE: https://github.com/microsoft/promptflow/issues/2299
The 
TEST PLAN:
updated md file renders in vscode, copy & paste of corrected command line works when a real run name is used.
- [x ] Pull request includes test coverage for the included changes. (N/A)
> Fix docs cli example to give the promised run details table output

- src/promptflow/promptflow/_sdk/_service/apis/collector.py
- src/promptflow/promptflow/_sdk/_service/app.py
1. Add name in created_by info (For UI show)
2. Call method to get created_by in each request instead of starting service
As info required by local to cloud trace, don't depend on Configuration file is clearer.
> Improve created_by info for local to cloud trace

- src/promptflow/promptflow/_cli/_pf/_experiment.py
- src/promptflow/promptflow/_sdk/_load_functions.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
1. Change experiment cli "--file" to "--template"
2. pf experiment start --template, create a new experiment
> [Experiment] Change experiment cli "--file" to "--template"

- docs/how-to-guides/develop-a-tool/create-dynamic-list-tool-input.md
- examples/tools/tool-package-quickstart/my_tool_package/tools/tool_with_dynamic_list_input.py
- src/promptflow-tools/promptflow/tools/open_model_llm.py
Issue: #2238 
Fix: 
- if no workspace triad available, return empty list.
- set default values to workspace triad params of dynamic list tool func.
After fix:
> [BugFix] set default values to workspace triad params of dynamic list tool func to avoid misleading errors

- src/promptflow/promptflow/_core/log_manager.py
This pull request includes a change to the `write` method in the `log_manager.py` file. The change adds a check for `None` to avoid errors when the line execution timeout is reached and all running nodes are cancelled. This is necessary because for synchronous tools running in a worker thread, they can't be stopped and the context won't change in the worker thread as it's a thread-local variable.
> Add null check for StringIO in case of line execution timeout.

- src/promptflow/promptflow/_sdk/_tracing.py
Do not add otlp exporter when the environment is not set.
Currently we will initialize an exporter with `endpoint=None`, then we will call a default http endpoint.
However we need to avoid this.
> [Bugfix] Do not add otlp exporter if the env is not set to avoid the default http endpoint.

- scripts/docs/conf.py
Add a hyper link point to promptflow chatbot in pf docsite.
> [Internal] add hyper link to pf chatbot in pf docsite

- src/promptflow/promptflow/_sdk/entities/_trace.py
- src/promptflow/tests/sdk_pfs_test/e2etests/test_trace.py
Rename this field to make UX easier to work with line run; will keep both `display_name` and `name` for now to avoid temp breaking, and will remove `display_name` once we get UX bundle updated.
> [tracing] Rename `display_name` to `name` in line run evaluations

- src/promptflow/promptflow/_constants.py
- src/promptflow/promptflow/azure/_storage/cosmosdb/summary.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_summary.py
Create a running placeholder item in LineSummary table.
Then if line run needs to execute a long time, customer could see it in advance in UI.
This PR also add special logic for inserting evaluations. We only insert it after find the main flow is `Ok`.
Because when main flow is finished, we need to invoke upsert_item, which will override existing `evaluations`.
Only insert evaluations when main flow is `Ok` could avoid missing data.
> Create running placeholder item in LineSummary table

- src/promptflow/promptflow/tracing/_utils.py
Since the promptflow-tracing package should only depend on openai and opentelemetry, we should remove the dependence of tracing on jinja2.
> [Tracing] Remove dependence of tracing on jinja2

- src/promptflow-tools/tests/test_open_model_llm.py
This PR skips the test_open_model_llm tests to unblock `tools_tests` gated pipeline as they require new test resources.
> Skipping test_open_model_llm.TestOpenModelLLM tests as they require new test resources

- src/promptflow/promptflow/executor/_line_execution_process_pool.py
- Fix the start_flow_run parameter.
> [ProcesPool] Fix start flow run param

- src/promptflow/setup.py
Upgrade some azure deps to align the deps with promptflow runtime. And then runtime can remove some self define deps version.
> [Internal] Align the extras_require with azure promptflow

- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_constants.py
- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/operations/_local_storage_operations.py
- src/promptflow/promptflow/_utils/logger_utils.py
- src/promptflow/promptflow/executor/_line_execution_process_pool.py
- src/promptflow/tests/executor/e2etests/test_logs.py
Open another PR
There is one can't resolve conversation in original PR
https://github.com/microsoft/promptflow/pull/2323
Add separate log for each line in batch run. Which could improve user experience for debugging failed lines.
In future, it could also be useful to check eager flow's customer print content.
Local batch run flow logs folder example:
Use fixed length file name to keep right order, then it could be easier to check.
Implementation:
There are 3 loggers in executor ("execution"\"execution.flow"\"execution.bulk")
They all have handler list to write log.
Such as `FileHandlerConcurrentWrapper` and `StreamHandler`.
`FileHandlerConcurrentWrapper` is wrapper for `FileHandler`.
Before this PR, we use `FileHandlerConcurrentWrapper` to write bulk run's log content to same file.
In …
> Add separate log for each line in batch run.

- src/promptflow/promptflow/_core/tools_manager.py
- src/promptflow/tests/executor/unittests/_core/test_tools_manager.py
Issue, currently the register_apis only support below api which only have one connection type:
But we have a requirement to change the connection to Union to include ServerlessConnection like below:
So here make change to let the register_apis support Union connections.
Add UT for it.
> [Internal] Support Union connections for register_apis

- src/promptflow/promptflow/_sdk/entities/_flow/_flow_context_resolver.py
- src/promptflow/promptflow/_sdk/entities/_flow/base.py
- src/promptflow/promptflow/core/_flow.py
- src/promptflow/promptflow/core/_serving/app.py
- src/promptflow/promptflow/core/_serving/flow_invoker.py
- src/promptflow/tests/sdk_cli_test/unittests/test_flow_invoker.py
This PR is to revert args for `FlowInvoker.__init__`, which change will bring [compatibility issue with `mlflow`](https://github.com/mlflow/mlflow/blob/master/mlflow/promptflow/__init__.py#L401).
Given this is a refactor of a private class which has already been tested explicitly and implicitly in many tests, we haven't added new tests here.
This pull request primarily focuses on refactoring the flow invocation process in the `promptflow` package. The changes aim to simplify the codebase by introducing an `AbstractFlowBase` class, removing redundant parameters and methods, and adjusting the way flows are initialized and invoked.
Refactoring flow invocation:
* [`src/promptflow/promptflow/_sdk/entities/_flow/_flow_context_resolver.py`](diffhunk://#diff-a1a6133992adb765818f3a6474d0f2a1468a609 …
> fix: avoid lazy shutdown for executor proxy in local pfs flow test

- src/promptflow-tracing/promptflow/tracing/_integrations/_openai_injector.py
- src/promptflow-tracing/promptflow/tracing/_trace.py
- src/promptflow-tracing/promptflow/tracing/_tracer.py
- src/promptflow-tracing/promptflow/tracing/contracts/trace.py
- src/promptflow-tracing/tests/e2etests/simple_functions.py
- src/promptflow-tracing/tests/e2etests/test_tracing.py
- src/promptflow-tracing/tests/unittests/test_openai_injector.py
- src/promptflow-tracing/tests/unittests/test_trace.py
Rename openai spans since openai.resources.chat.Completions.create is too long.
This pull request primarily introduces changes to the tracing functionality in the `promptflow` application. The changes allow for more flexibility and control over the naming of traces, particularly for asynchronous and synchronous functions. The key changes can be grouped into two categories: modifications to the function definitions and adjustments to the function calls.
Modifications to function definitions:
* [`src/promptflow-tracing/promptflow/tracing/_trace.py`](diffhunk://#diff-580941184737186a94e3e9c06e467e86c06ce846d30ffa42c1c43b45812ddcdcL272-R276): Both the `_traced_async` and `_traced_sync` functions were modified to include an optional `name` parameter. This allows for custom naming of the …
> [Draft][Tracing] Modify openai span names

- .github/workflows/promptflow-sdk-cli-test.yml
- .github/workflows/sdk-cli-azure-test-pull-request.yml
- src/promptflow-tracing/promptflow/tracing/_integrations/_openai_injector.py
- src/promptflow-tracing/promptflow/tracing/_trace.py
- src/promptflow-tracing/promptflow/tracing/_tracer.py
- src/promptflow-tracing/promptflow/tracing/contracts/trace.py
- src/promptflow-tracing/tests/e2etests/simple_functions.py
- src/promptflow-tracing/tests/e2etests/test_tracing.py
- src/promptflow-tracing/tests/unittests/test_openai_injector.py
- src/promptflow-tracing/tests/unittests/test_trace.py
- src/promptflow/tests/sdk_cli_test/recording_utilities/openai_inject_recording.py
Rename openai spans since openai.resources.chat.Completions.create is too long.
This pull request primarily introduces changes to the tracing functionality in the promptflow application. The changes allow for more flexibility and control over the naming of traces, particularly for asynchronous and synchronous functions. The key changes can be grouped into two categories: modifications to the function definitions and adjustments to the function calls.
Modifications to function definitions:
[src/promptflow-tracing/promptflow/tracing/_trace.py](https://github.com/microsoft/promptflow/pull/2424/files#diff-580941184737186a94e3e9c06e467e86c06ce846d30ffa42c1c43b45812ddcdcL272-R276): Both the _traced_async and _traced_sync functions were modified to include an optional name parameter. This allows …
> [Tracing] Modify openai span names

- src/promptflow/promptflow/batch/_batch_engine.py
Since we switch to load previous_run_output from debug_info instead of output file, the resume_from_output_dir is not used in the resume process. This PR removes it from _copy_previous_run_result.
To maintain consistency with runtime and not introducing breaking change, we keep it in the batch_engine.run param list.
> [Executor] Remove resume_from_run_output_dir

- src/promptflow-tracing/promptflow/tracing/_openai_utils.py
- src/promptflow/setup.py
- src/promptflow/tests/executor/e2etests/test_traces.py
- src/promptflow/tests/executor/unittests/batch/test_result.py
We have modified openai api name in this [PR](https://github.com/microsoft/promptflow/pull/2459), so we also need to change other places used these names.
> Use new openai api name in metrics calculator and tests

- src/promptflow/promptflow/_internal/__init__.py
When we support tracing API in promptflow-runtime, we have some dependencies of promptflow. We add the dependencies at promptflow._internal.
> [Internal] Add runtime dep of tracing to promptflow._internal

- src/promptflow/promptflow/_core/run_tracker.py
Update the corresponding error to node run info when async node is canceled.
> [Internal][Executor] Update the corresponding error to node run info when async node is canceled

- src/promptflow/promptflow/_constants.py
- src/promptflow/promptflow/_internal/__init__.py
- src/promptflow/promptflow/_sdk/_constants.py
- src/promptflow/promptflow/_sdk/_service/apis/collector.py
- src/promptflow/promptflow/_sdk/_service/app.py
- src/promptflow/promptflow/_sdk/_tracing.py
- src/promptflow/promptflow/azure/_storage/cosmosdb/collection.py
- src/promptflow/promptflow/azure/_storage/cosmosdb/cosmosdb_utils.py
- src/promptflow/promptflow/azure/_storage/cosmosdb/span.py
- src/promptflow/promptflow/azure/_storage/cosmosdb/summary.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_collection.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_cosmosdb_utils.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_span.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_summary.py
We need a new concept (Collection/trace group) to save non-batch run's traces.
For batch run, UX could use info provided by RH to aggregate.
For non-batch run, we create a collection table to record info such as `created_by` and `updated_at`.
> Write collection container for portal trace

- src/promptflow-tracing/promptflow/tracing/_trace.py
In current implementation, an error will be raised:
Invalid type ChatCompletionMessage for attribute 'llm.generated_message' value. Expected one of ['bool', 'str', 'bytes', 'int', 'float'] or a sequence of those types
This bug is because we forgot to serialize the value.
This pull request includes a modification to the `enrich_span_with_llm` function in the `src/promptflow-tracing/promptflow/tracing/_trace.py` file. The change involves using the `serialize_attribute` function on the `generated_message` before setting it as an attribute of the `span`. This should help in ensuring that the `generated_message` is in a format suitable for being set as an attribute.
> [Bugfix][Tracing] Fix the bug that generated message set failed.

- src/promptflow-tracing/promptflow/tracing/_trace.py
- src/promptflow-tracing/tests/e2etests/test_tracing.py
This pull request introduces changes to the tracing functionality in PromptFlow. Specifically, it adds input and output events to the OpenTelemetry spans. The event names are `promptflow.function.inputs` and `promptflow.function.output`, and their attributes contain a payload which is a JSON dump of the input/output values. This enhancement will provide more detailed tracing information and facilitate debugging and performance monitoring.
This PR also includes updates to the relevant unit tests to validate these new events and their payloads.
> Add Input/Output Events to OpenTelemetry Spans in PromptFlow

- src/promptflow/promptflow/executor/_service/apis/common.py
- src/promptflow/promptflow/executor/_service/utils/service_utils.py
- src/promptflow/tests/executor/unittests/executor/_service/apis/test_common.py
- src/promptflow/tests/executor/unittests/executor/_service/utils/test_service_utils.py
> [Internal][Executor] Add commit id to version api

- src/promptflow-core/promptflow/executor/_line_execution_process_pool.py
- src/promptflow-core/promptflow/executor/flow_executor.py
Setting up exporter as creating executor.
Then we could skip setting up it in many places.
Will use e2e test to cover this scenario.
> Add setup exporter logic as creating executor

- src/promptflow-devkit/promptflow/_sdk/_constants.py
- src/promptflow-devkit/promptflow/_sdk/_service/apis/flow.py
- src/promptflow-devkit/promptflow/_sdk/_submitter/test_submitter.py
- src/promptflow-devkit/promptflow/_sdk/data/executable/main.py
- src/promptflow-devkit/promptflow/_sdk/entities/_flow/dag.py
- src/promptflow-devkit/promptflow/_sdk/operations/_flow_operations.py
- src/promptflow-devkit/promptflow/batch/_base_executor_proxy.py
- src/promptflow-devkit/promptflow/batch/_csharp_executor_proxy.py
Although new chat UI doesn't support streaming for now, PFS will call flow operation with `stream_output` as `True`, which may bring some issues in resource release. In this PR, we avoid that.
Improvements to the `TestSubmitter`:
* [`src/promptflow/promptflow/_sdk/_submitter/test_submitter.py`](diffhunk://#diff-d9dd2c09a149b11eb54626edf065287eeb7b1a28e39719b8dd95377770f64138R287-R289): The `destroy_if_all_generators_exhausted` method has been replaced with the `destroy` method in the `TestSubmitter` class. This change is accompanied by a comment noting that the current implementation may not properly release resources.
Changes to the test submission process:
* [`src/promptflow/promptflow/_sdk/data/executable/main.py`](diffhunk://#diff-c22ed7aec6ed0b5a5fde51716818d5695b917ab38cc385ee7e65390 …
> fix: always release resources in chat ui for csharp

- src/promptflow-tracing/promptflow/tracing/_start_trace.py
- src/promptflow/tests/sdk_cli_test/unittests/test_trace.py
This pull request primarily focuses on enhancing the tracing functionality in the `promptflow` module. The main changes are in the `src/promptflow-tracing/promptflow/tracing/_start_trace.py` file. The changes include importing the `OTEL_EXPORTER_OTLP_ENDPOINT` from `opentelemetry.sdk.environment_variables` and modifying the `setup_exporter_from_environ()` function to skip the setup if the `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable is not set.
Changes in detail:
* [`src/promptflow-tracing/promptflow/tracing/_start_trace.py`](diffhunk://#diff-7af0034cfa004d9b472906d191838650ce1a8bacaf3f90ec5fc2479a0a8ef909R11-R12): Imported `OTEL_EXPORTER_OTLP_ENDPOINT` from `opentelemetry.sdk.environment_variables`. This environment variable is used to determine the endpoint for OpenTelemetry.
* …
> [Tracing][Internal] Skip otel setup if no environment is set

- .github/workflows/promptflow-import-linter.yml
Fix breaking import linter CI workflow by touching `__init__.py`.
> [fundamental][bugfix] Fix breaking import linter CI workflow

- scripts/docs/doc_generation.ps1
- src/promptflow-devkit/promptflow/_sdk/_orm/trace.py
There are lots of users/packages still dependent on SQLAlchemy 1.x, previous pull request introduces 2.x style only ORM syntax, which may lead to some issues. This PR targets to back to the 1.x style for ORM, so that we don't need to make promptflow depend on SQLAlchemy 2.x only.
> [devkit][bugfix] Use SQLAlchemy 1.x style ORM

- src/promptflow-core/promptflow/_core/run_tracker.py
- src/promptflow-core/promptflow/contracts/run_info.py
- src/promptflow-core/promptflow/executor/flow_executor.py
- src/promptflow-tracing/promptflow/tracing/_trace.py
Use otel_trace_id for correlation between line run and otel trace.
This pull request primarily focuses on enhancing the traceability of operations in the codebase. The changes involve storing the OpenTelemetry (otel) trace ID in the PromptFlow (pf) trace for correlation. This is achieved by introducing the `OperationContext` class and adding the `otel_trace_id` attribute to the `FlowRunInfo` class.
Here are the key changes:
Traceability enhancements:
* [`src/promptflow-core/promptflow/_core/run_tracker.py`](diffhunk://#diff-a5027d19a24cb28a68ead16dfe6c54492c78d6e0e7640e80533928808cdb3422R25): Imported `OperationContext` class and stored the otel trace ID in pf trace for correlation in the `_flow_run_postprocess` method. [[1]](diffhunk://#diff-a5027d19a24cb28a68ead16dfe6c54492c78d6e0e7640e8 …
> [Tracing][Internal] Use otel_trace_id for correlation between line run and otel trace

- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/collection.py
- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/summary.py
- src/promptflow-devkit/promptflow/_sdk/_service/apis/collector.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_collection.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_summary.py
Set batch run id as partition key for local batch run. 
Because we need a separate partition key for batch run from flow test in case of cosmosDB's 20GB limitation.
Remove partition key condition for eval run insertion query.
As evaluation flow, we can't know the specific partition key for main flow.
> Use batch run id as partition key for local batch run

- src/promptflow-azure/README.md
- src/promptflow-core/README.md
- src/promptflow-devkit/README.md
- src/promptflow-tracing/README.md
> refine READMEs for the subpackages

- docs/dev/dev_setup.md
- scripts/dev-setup/main.py
- src/promptflow-core/pyproject.toml
- Add a parameter `vscode` for dev setup script, so that the script will not automatically touch those `__init__.py` files.
- Bump `promptflow-core` version to 1.1.0.dev0 following the new version design/decision.
> [fundamental][bugfix] Refine dev setup script to not automatically touch `__init__.py`

- src/promptflow-core/promptflow/_utils/multimedia_utils.py
- src/promptflow/tests/executor/unittests/_utils/test_multimedia_utils.py
Fix some bugs caused by this pr  https://github.com/microsoft/promptflow/pull/2287
1. Fix MultimediaProcessor._process_multimedia_dict_recursively.
2. Because this pr 2287 fully refactored multimedia_utils, some changes made to the file by others during development were ignored. Specific changes:
- https://github.com/microsoft/promptflow/pull/2122
- Remove `*,` for `get_file_reference_encoder` method.
- Add parameter: `use_absolute_path` for `persist_multimedia_data` method.
> Fix multimedia_utils.

- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/summary.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_summary.py
Use batch run id as evaluation dict's key for batch run.
https://int.ml.azure.com/prompts/trace/list?wsid=/subscriptions/96aede12-2f73-41cb-b983-6d11a904839b/resourceGroups/promptflow/providers/Microsoft.MachineLearningServices/workspaces/promptflow-canary-dev&searchText={%22batchRunId%22:%22test_main_variant_0_20240401_095544_611576%22}&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
Current UX can't show eval output in LineSummary list after this change.
Because UX will update to new UI soon, we accept this breaking change.
> Use batch run id as evaluation dict's key for batch run.

- src/promptflow-devkit/promptflow/_sdk/entities/_trace.py
For eval line run(s), use run name, instead of root span name.
> [tracing][bugfix] Use eval run name instead of root span name

- src/promptflow-devkit/promptflow/_internal/__init__.py
Add CosmosDBContainerName to promptflow._internal for runtime to use. This is for checking if the db has init.
> [Internal] Add CosmosDBContainerName to promptflow._internal

- src/promptflow-core/promptflow/executor/flow_executor.py
Add trace force flush for `execute_flow`.
For multi container scenario, we may fail to export traces because process terminated directly.
Why we need to manually invoke force flush:
Seems like when we create worker process by `invoke_sync_function_in_process`, the atexit method registered by tracer provider is not invoked. Fix this issue by adding force flush first, it's recommended by GPT to handle it manually for multi process scenario.
Why use force flush but not shutdown:
In case of customer execute_flow manually in their code.
> Force flush traces for execute_flow

- src/promptflow-core/promptflow/executor/_script_executor.py
- src/promptflow/tests/executor/e2etests/test_logs.py
- src/promptflow/tests/executor/utils.py
- src/promptflow/tests/test_configs/eager_flows/print_input_flex/flow.dag.yaml
- src/promptflow/tests/test_configs/eager_flows/print_input_flex/inputs.jsonl
- src/promptflow/tests/test_configs/eager_flows/print_input_flex/print_input_flex.py
Use NodeLogManager to redirect customer print content for flex run.
Then customer could see print content in log file.
We will print the content to `flow_logger` or `logger`.
> Redirect print content to log for flex.

- src/promptflow-devkit/promptflow/_sdk/_service/apis/collector.py
- src/promptflow-devkit/promptflow/_sdk/entities/_trace.py
- src/promptflow-devkit/promptflow/_sdk/operations/_trace_operations.py
- src/promptflow/tests/sdk_cli_test/unittests/test_trace.py
This PR moves the functions that parse protobuf span/events/links from span entity to trace operations; **ALSO**, pass logger along with these functions so that we can have more logs during parse, and we can know more when OTLP trace collector in PFS - which can make debug easier in the future.
**what will be printed in PFS debug logs**
> [devkit][refactor] Move protobuf span parse function to trace operation

- src/promptflow-core/promptflow/executor/_line_execution_process_pool.py
- src/promptflow-core/promptflow/executor/flow_executor.py
If customer don't use tracer provider, otel will return ProxyTracerProvider, which doesn't have `shutdown` `force_flush` method.
Add hasattr check to guarantee the tracer provider has necessary methods.
> Skip flushing if tracer provider doesn't have method

- src/promptflow-evals/promptflow/evals/evaluators/coherence/flow/flow.dag.yaml
- src/promptflow-evals/promptflow/evals/evaluators/coherence/flow/validate_inputs.py
- src/promptflow-evals/promptflow/evals/evaluators/content_safety/flow/flow.dag.yaml
- src/promptflow-evals/promptflow/evals/evaluators/content_safety/flow/validate_inputs.py
- src/promptflow-evals/promptflow/evals/evaluators/f1_score/flow/validate_inputs.py
- src/promptflow-evals/promptflow/evals/evaluators/fluency/flow/flow.dag.yaml
- src/promptflow-evals/promptflow/evals/evaluators/fluency/flow/validate_inputs.py
- src/promptflow-evals/promptflow/evals/evaluators/groundedness/flow/flow.dag.yaml
- src/promptflow-evals/promptflow/evals/evaluators/groundedness/flow/validate_inputs.py
- src/promptflow-evals/promptflow/evals/evaluators/relevance/flow/flow.dag.yaml
- src/promptflow-evals/promptflow/evals/evaluators/relevance/flow/validate_inputs.py
- src/promptflow-evals/promptflow/evals/evaluators/similarity/flow/flow.dag.yaml
- src/promptflow-evals/promptflow/evals/evaluators/similarity/flow/validate_inputs.py
> Update built-in evaluators' inputs validation logic and remove default values

- src/promptflow-devkit/promptflow/_cli/_pf/_trace.py
- src/promptflow-devkit/promptflow/_sdk/operations/_trace_operations.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_trace.py
This PR targets to refine the experience on CLI command `pf trace delete`:
- Prompt how many traces will be deleted with the given parameters
- Print error message when parameters are wrongly specified
> [devkit] Refine CLI `pf trace delete` experience

- .github/CODEOWNERS
This pull request includes a few changes to the `.github/CODEOWNERS` file. The changes mostly involve reassigning code ownership for several directories and files within the `promptflow` project.
* `/src/promptflow-devkit/promptflow/_proxy/` has been reassigned from solely `@microsoft/promptflow-execution` to both `@microsoft/promptflow-execution` and `@microsoft/promptflow-sdk`.
* New ownership assignments have been added for the following files: 
* `/src/promptflow/tests/executor/_prompty_executor.py` is now owned by `@microsoft/promptflow-sdk`.
* `/src/promptflow/tests/executor/_script_executor.py` is now owned by `@microsoft/promptflow-sdk`.
* `/src/promptflow-tracing/promptflow/tracing/_start_trace.py` is now owned by `@microsoft/promptflow-sdk`.
* The ownership assignment for …
> fix: add codeowners for sdk

- src/promptflow-azure/promptflow/azure/_restclient/flow_service_caller.py
- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_run_operations.py
In this PR, we init FlowRequestException with _inner_exception by param error. 
And then, we can use e.inner_exception for error handling.
> [Internal] Init FlowRequestException with _inner_exception.

- src/promptflow-core/promptflow/executor/_script_executor.py
- src/promptflow-core/promptflow/executor/flow_executor.py
- src/promptflow-core/tests/core/e2etests/test_eager_flow.py
- src/promptflow-devkit/promptflow/batch/_batch_engine.py
Allow passing a function/callable instance to executor.
This pull request involves changes primarily in the `src/promptflow-core/promptflow/executor/_script_executor.py` and `src/promptflow-devkit/promptflow/batch/_batch_engine.py` files, with the goal of expanding the types of entries that can be accepted by the `ScriptExecutor` and `BatchEngine` classes, and updating the relevant methods to handle these new types. The changes also include additions to the test file `src/promptflow-core/tests/core/e2etests/test_eager_flow.py` to ensure the new functionality works as expected.
Here are the key changes:
Expanded Entry Types:
* [`src/promptflow-core/promptflow/executor/_script_executor.py`](diffhunk://#diff-ee8f37478601ef45fdb2e773f04b280f5912f43868da4d5f1c4cf888a9980ab4L36-R36): The …
> [Executor][Feature]Allow function/instance as the entry of script executor

- src/promptflow-tools/promptflow/tools/common.py
- src/promptflow-tools/promptflow/tools/llm.py
- src/promptflow-tools/promptflow/tools/llm_vision.py
Issue: new llm cannot work with serverless connection error.
Root cause: fallback in executor just work from old llm.
Fix:
> fix serverless connection does not work issue

- src/promptflow-recording/promptflow/recording/azure/bases.py
- src/promptflow/tests/sdk_cli_azure_test/e2etests/test_cli_with_azure.py
This PR targets to refine tests:
- `promptflow-recording` not work in non-editable mode: when file path has "site-packages", we regard it as in non-editable mode, in this case, we will navigate to the recording files from test file.
- For flaky Azure test `test_cli_telemetry`: this error might happen in concurrency, so add a retry logic to try to resolve this.
> [test][bugfix] Fix promptflow-recording not work in non-editable mode & try to fix a flaky test

- src/promptflow-core/promptflow/contracts/run_info.py
If `root_run_id` is equal to `run_id`, runtime will not persist flow run, so we should use `line_run_id` as run_id when creating line result with error.
> [Bugfix][Executor] Change the run id to line run id when creating line result with error

- src/promptflow-core/promptflow/executor/_service/apis/batch.py
- src/promptflow-core/promptflow/executor/_service/apis/execution.py
- src/promptflow-core/promptflow/executor/_service/contracts/execution_request.py
- src/promptflow-core/promptflow/executor/_service/utils/batch_coordinator.py
- src/promptflow/tests/executor/unittests/executor/_service/utils/test_batch_coordinator.py
After https://github.com/microsoft/promptflow/pull/2658, we enable setting flow name by payload.
But for multi container scenario, we need to pass `flow_name` by http request.
In this PR, add `flow_name` field in contract and use it to create executor.
Validation:
https://int.ml.azure.com/prompts/trace/list?wsid=%2Fsubscriptions%2F96aede12-2f73-41cb-b983-6d11a904839b%2FresourceGroups%2Fpromptflow%2Fproviders%2FMicrosoft.MachineLearningServices%2Fworkspaces%2Fpeiwen-ws&searchText=%7B%22sessionId%22%3A%22%22%7D&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
> Apply flow_name for multi container execution

- src/promptflow-core/pyproject.toml
search install docutils 0.21.post1
ignore import linter since it depends on online version of promptflow-core, which may install docutils 0.21.post1
> Limit docutils since newer version is breaking

- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/span.py
- src/promptflow/tests/sdk_cli_azure_test/unittests/test_span.py
This PR add the `to_cosmosdb_item` method in the `Span` class, ensuring that attribute values are truncated to a specified maximum length. This change is critical to prevent exceeding CosmosDB's 2MB item size limit. The `attr_value_truncation_length` parameter allows for flexible adjustment of the truncation threshold, accommodating different use cases and requirements.
By merging this PR, we will improve the reliability of our telemetry data storage in CosmosDB, especially for larger spans that previously risked rejection due to size limitations. The code aligns with the serialization method used by the CosmosDB Python SDK, ensuring compatibility and consistency across our application.
> Implement Attribute Truncation in to_cosmosdb_item to Comply with CosmosDB Size Limit

- src/promptflow-core/promptflow/_core/tool_meta_generator.py
- src/promptflow-core/promptflow/_utils/tool_utils.py
- src/promptflow-devkit/promptflow/_sdk/operations/_flow_operations.py
- src/promptflow-devkit/promptflow/_sdk/schemas/_flow.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_cli.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_save.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_serve.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_test.py
- src/promptflow/tests/test_configs/eager_flows/basic_callable_class/simple_callable_class.py
- src/promptflow/tests/test_configs/eager_flows/dummy_flow_with_trace/flow_with_trace.meta.json
- src/promptflow/tests/test_configs/eager_flows/dummy_flow_with_trace/flow_with_trace.py
- src/promptflow/tests/test_configs/eager_flows/multiple_stream_outputs/multiple_stream_outputs.py
- src/promptflow/tests/test_configs/eager_flows/simple_with_dict_output/dict_output_entry.py
- src/promptflow/tests/test_configs/functions/class_init_complicated_ports/hello.py
- src/promptflow/tests/test_configs/functions/class_init_with_entity_init/hello.py
This PR includes 3 changes:
1. treat `TypedDict` in the same way as `dataclass`. Below 3 functions will get the same signature. This support **will not be applied to tools** for now as such support is for output only and we don't generate output signature for tools.
```python
from typing import TypedDict
from dataclasses import dataclass
class TypedOutput(TypedDict):
s: str
@dataclass
class DataOutput:
s: str
def hello_typed_dict_inline(str text) -> TypedDict("TypedOutput", {"s": str}):
pass
def hello_typed_dict(str text) -> TypedOutput:
pass
def hello_dataclass(str text) -> DataOutput:
pass
```
2. change the expected signature for primitive flow output:
```json
{
"inputs": ...
"outputs": {"output": {"type": "string"}}
}
```
=>
```json
{
"inputs": ...
}
```
3. support `list` and `dict` in …
> feat: support TypedDict as flex flow return type

- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/client.py
When call get cosmos db token API, we found that sometimes we will met timeout. The default connection_timeout and read_timeout are both 300s([code](https://github.com/Azure/azure-sdk-for-python/blob/9fa8967963f263d6211f1d566b41f46fe7cf27bf/sdk/core/azure-core/azure/core/configuration.py#L109)).
In this PR, we set the connection_timeout to 15s and read_timeout to 30s to reduce the possible latency when met timeout.
> [Internal] Set timeout when getting cosmos db token 

- src/promptflow-devkit/promptflow/_sdk/operations/_flow_operations.py
- src/promptflow-devkit/promptflow/_sdk/schemas/_flow.py
- src/promptflow/tests/sdk_cli_test/e2etests/test_flow_save.py
Use flow-dag-yaml type system for pf.flows.infer_signature and pf.flows.save before service-side done related support
> revert: use dag type system for infer_signature

- docs/reference/pf-command-reference.md
- src/promptflow-azure/promptflow/azure/operations/_run_operations.py
- src/promptflow-core/promptflow/_constants.py
- src/promptflow-core/promptflow/core/_connection_provider/_utils.py
- src/promptflow-core/promptflow/core/_connection_provider/_workspace_connection_provider.py
- src/promptflow-core/promptflow/core/_errors.py
- src/promptflow-core/promptflow/core/_serving/extension/azureml_extension.py
- src/promptflow-devkit/CHANGELOG.md
- src/promptflow-devkit/promptflow/_sdk/entities/_run.py
- src/promptflow-devkit/promptflow/_sdk/operations/_local_azure_connection_operations.py
- src/promptflow-recording/promptflow/recording/azure/utils.py
- src/promptflow-recording/recordings/azure/test_arm_connection_operations_TestArmConnectionOperations_test_get_connection.yaml
- src/promptflow-recording/recordings/azure/test_workspace_connection_provider_TestWorkspaceConnectionProvider_test_list_connections.yaml
- src/promptflow/CHANGELOG.md
- Refine workspace connection provider error handling
- Fix run name get dir name empty error
- Limit workspace type to 'project' and 'default' if use workspace connection
> Add some package and resource checks

- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/summary.py
Use None for span_type's default value. For customer created span, span_type is not always exist.
Use `None` as default value to align with local sdk.
> Fix unset span_type. Align default value with local sdk

- src/promptflow-devkit/promptflow/_sdk/_orchestrator/run_submitter.py
- src/promptflow-devkit/promptflow/_sdk/_pf_client.py
- src/promptflow-devkit/promptflow/_sdk/entities/_run.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_flow_run.py
Support `pf.run` for dynamic callable. If the callable entry is dynamic, we won't support resume for it.
> feat: support pf.run for dynamic callable

- src/promptflow-devkit/promptflow/_proxy/_csharp_executor_proxy.py
- src/promptflow-devkit/promptflow/_proxy/_csharp_inspector_proxy.py
In csharp executor service, traces are sent in parallel with exec response, so it is possible that traces are not fully sent when we try to destroy the executor proxy. To avoid this, we need to enable graceful shutdown for csharp.
To enable graceful shutdown (supported in windows only for now), csharp required a `CTRL_C_EVENT` signal instead of `SIGTERM` signal, which will forcefully shutdown the csharp service.
On the other hand, directly sending `CTRL_C_EVENT` signal will touch all processes in target process group so the main process will also be terminated.
We fix this issue in this PR
> fix: csharp graceful shutdown

- src/promptflow-devkit/promptflow/_sdk/_orm/trace.py
- src/promptflow-devkit/promptflow/_sdk/_service/apis/line_run.py
- src/promptflow-devkit/promptflow/_sdk/operations/_trace_operations.py
- src/promptflow-devkit/tests/sdk_pfs_test/e2etests/test_trace.py
- src/promptflow-devkit/tests/sdk_pfs_test/utils.py
Support `session=<session>` in PFS API `/v1.0/LineRuns/list`, so that UX can query those traces with specified session id.
> [trace] Support list line runs with new session id

- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/summary.py
- src/promptflow-azure/tests/sdk_cli_azure_test/unittests/test_summary.py
- src/promptflow-core/promptflow/_constants.py
- src/promptflow-core/promptflow/executor/_service/utils/batch_coordinator.py
- src/promptflow-core/promptflow/executor/flow_executor.py
- src/promptflow-devkit/promptflow/_proxy/_python_executor_proxy.py
- src/promptflow-devkit/tests/sdk_cli_test/unittests/test_pf_client.py
1. Add batch run id for aggregate node, to guarantee don't touch collection table.
2. Add attribute to mark is aggregation or not. For aggregate node, we don't write `LineSummary`. **Then we could hide it from UX list. This is the motivation for this PR**
3. Delete `_exec_aggregation_with_bulk_results` method, used by nowhere.
4. Use `exec_aggregation` instead of `_exec_aggregation` for better code structure.
> Update operation context for aggregation node

- src/promptflow-evals/samples/evaluation.py
> [promptflow-evals] Update a missing sample file for the model config change

- src/promptflow-azure/promptflow/azure/_utils/_tracing.py
- src/promptflow-core/promptflow/_constants.py
- src/promptflow-devkit/promptflow/_sdk/_configuration.py
- src/promptflow-devkit/promptflow/_sdk/_tracing.py
- src/promptflow-devkit/promptflow/_sdk/_tracing_utils.py
- src/promptflow-devkit/tests/sdk_cli_test/unittests/test_trace.py
**Local cache for Azure ML workspace/AI project type**
Local cache resource type, so that we don't need to request Azure everytime. There is a timeout 1 day, so that we can avoid missing the Cosmos status in the future.
**Support `trace.provider=local`**
Enable local only trace feature.
> [trace][feature] Local cache for workspace kind & support `trace.provider=local`

- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_cli.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_flow_save.py
compare set instead of list to make test_flow_save_file_code more stable
> fix: test_flow_save_file_code

- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/summary.py
- src/promptflow-azure/tests/sdk_cli_azure_test/unittests/test_summary.py
Keep same behavior with local trace.
Use same structure for main flow and evaluation value in LineSummary. 
Maybe could free us from adding fields one by one.
> Use same structure for main flow and evaluation value in LineSummary

- src/promptflow-evals/tests/evals/conftest.py
- src/promptflow-tools/tests/conftest.py
- src/promptflow/tests/_constants.py
> Fix typo that causes error in pytest collection

- src/promptflow-tools/promptflow/tools/common.py
- src/promptflow-tools/tests/test_handle_openai_error.py
Issue: Customer found no retry when he met APIConnectionError "httpcore.RemoteProtocolError: Server disconnected without sending a response".
Root cause: We only retry on APIConnectionError if the error message contains "connection aborted" or it is APITimeOutError.
Solution: 
Considering not all APIConnectionError is retriable, for example, if api_base is invalid, the error is not retriable.
Append "Server disconnected without sending a response" to retriable error.
> Allow retry for APIConnectionError "Server disconnected without sending a response"

- src/promptflow/tests/executor/e2etests/test_assistant.py
breaking changes from openai 1.21.2 which breaks assistant related tests. Skip for now to unblock CI.  Would deliver fix soon.
> Skip assistants e2e tests until fixing for openai breaking change release

- src/promptflow-core/promptflow/executor/flow_executor.py
Before, we load flow input image after creating root span. Which makes we only have input image's path for root span.
In this PR, we load flow input image in advance to record correct image data in root span.
> Convert input data in advance to make sure image is correct for root span

- .github/workflows/build_msi_installer.yml
- scripts/installer/windows/product.wxs
- scripts/installer/windows/scripts/generate_dependency.py
- scripts/installer/windows/scripts/stop_service.vbs
- Allow built-in evaluators work for C#: add pf-evals package into msi.
- Add stop promptflow service customaction to mitigate issue when windows installer can't detect pfs detach process and close it
> Add pf-evals package into msi

- scripts/check_enforcer/check_enforcer.py
We observe the CI are getting slower and slower, and as we target Build, we have little time to improve perf; so just make check-enforcer wait longer (from 15min to 20min), so that everyone does not need to rerun that workflow.
> [fundamental][bugfix] Make check-enforcer wait longer

- src/promptflow-core/promptflow/executor/_flow_nodes_scheduler.py
- src/promptflow-core/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/e2etests/test_batch_timeout.py
- src/promptflow/tests/executor/e2etests/test_concurent_execution.py
- src/promptflow/tests/executor/e2etests/test_logs.py
1. Record KeyboardInterrupt exception for span (otlp's code doesn't handle BaseException but only Exception)
2. Raise KeyboardInterrupt in FlowNodesScheduler
3. Remove `with ThreadPoolExecutor` to guarantee KeyboardInterrupt could be received by outside.
Why make this change: **we want to support cancellation for span.**
We have 2 schedulers, one is FlowNodesScheduler, another is AsyncNodesScheduler.
For most cases, we are using FlowNodesScheduler.
In FlowNodesScheduler, there is `with ThreadPoolExecutor`, which will wait all running threads finish, no matter what exception is raised. That's why our cancellation is blocked.
So, in this PR, remove the `with ThreadPoolExecutor` to make the KeyboardInterrupt could be received by outside.
Why also change other tests:
For now, our exception …
> Handle job cancellation for root span

- src/promptflow-core/promptflow/executor/_service/apis/batch.py
- src/promptflow-core/promptflow/executor/_service/apis/execution.py
- src/promptflow-core/promptflow/executor/_service/apis/tool.py
- src/promptflow-core/promptflow/executor/_service/contracts/tool_request.py
- src/promptflow-core/promptflow/executor/_service/utils/process_utils.py
- src/promptflow-core/promptflow/executor/_service/utils/service_utils.py
- src/promptflow/tests/executor/unittests/executor/_service/utils/test_process_utils.py
- src/promptflow/tests/executor/unittests/executor/_service/utils/test_service_utils.py
Now runtime put `PF_HTTP_CONNECTION_PROVIDER_ENDPOINT` in request.environment_variables, executor should set it in env to init a http connection provider. This is used for get connection in dynamic list scenario.
> Set PF_HTTP_CONNECTION_PROVIDER_ENDPOINT to env in retrieve_tool_func_result

- src/promptflow-azure/promptflow/azure/_storage/blob/client.py
- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/client.py
- src/promptflow-azure/promptflow/azure/_utils/_tracing.py
- src/promptflow-devkit/promptflow/_sdk/_service/app.py
- src/promptflow-tracing/promptflow/tracing/_start_trace.py
- For trace related credential, only use Azure CLI credential, which should be the only credential type we can rely on.
- Add back OpenAI instrument in `promptflow.tracing.start_trace`.
> [trace][bugfix] Always use Azure CLI credential for trace local to cloud scenario

- src/promptflow-devkit/promptflow/_sdk/_tracing.py
Currently we only print the url of the trace list, however we actually want to see the detail of each trace, so we add some logic to print such url including the trace id.
Flow test:
This pull request primarily focuses on enhancing the tracing capabilities in the `promptflow-devkit` by modifying the `src/promptflow-devkit/promptflow/_sdk/_tracing.py` file. The changes include the addition of new methods for generating tracing URLs, updating the `start_trace_with_devkit` method to set up URL templates, and creating a new class `OTLPSpanExporterWithTraceURL` to print trace URLs for each trace ID after they're exported to the server.
Key changes include:
Import Enhancements:
* [`src/promptflow-devkit/promptflow/_sdk/_tracing.py`](diffhunk://#diff-0851b3127a781742533fdff156aed857faa3cceb93a3e7 …
> [Tracing] Print trace detail url when exporting spans

- scripts/installer/windows/scripts/promptflow.spec.jinja2
- src/promptflow-devkit/promptflow/_sdk/_utils/general_utils.py
- src/promptflow-evals/promptflow/evals/_version.py
> Print evals version in pf and generate evals metafiles when package msi

- src/promptflow-azure/promptflow/azure/_storage/cosmosdb/summary.py
- src/promptflow-devkit/promptflow/_sdk/_tracing.py
1. Handle exception separately for each span, we don't want failure of one span make the whole batch spans fail
2. Change default value of latency to None. Current value is 0.0, which is misleading for UX rendering.
> Handle exception separately for each span

- scripts/dev-setup/main.py
Currently there are some corner case scenarios that `pip` is not in the subprocess environment. To avoid this issue, we directly use sys.executable to make sure we can use correct pip in the subprocess.
This pull request includes changes to the `scripts/dev-setup/main.py` file to improve the package installation process. The changes involve importing the `sys` module and modifying the `install_pkg_editable` function.
Key changes include:
* [`scripts/dev-setup/main.py`](diffhunk://#diff-a1c6a9229287822b824885bf66249fc20a47e850b3eb233bb2e9f63f65e4f41eR9): Imported the `sys` module to use the Python interpreter's executable for package installation.
* `def install_pkg_editable(pkg: str, verbose: bool, is_vscode: bool = False) -> No` in `scripts/dev-setup/main.py`: Modified the command used …
> [Internal] Use sys.executable to make sure dev setup use current env.

- src/promptflow-core/promptflow/executor/_script_executor.py
Provide exec_aggregation_async for script executor.
> [Executor] Provide exec_aggregation_async for script executor

- .github/workflows/promptflow-evals-e2e-test.yml
- .github/workflows/promptflow-evals-unit-test.yml
- .github/workflows/promptflow-release-testing-matrix.yml
- .github/workflows/promptflow-tracing-e2e-test.yml
- .github/workflows/promptflow-tracing-unit-test.yml
- .github/workflows/sdk-cli-perf-monitor-test.yml
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_prompty.py
- src/promptflow-recording/pyproject.toml
> Fix matrix, using recording even if it doesn't use it.

- src/promptflow-azure/tests/sdk_cli_azure_test/conftest.py
- src/promptflow-azure/tests/sdk_cli_azure_test/e2etests/test_flow_operations.py
- src/promptflow-azure/tests/sdk_cli_azure_test/e2etests/test_run_operations.py
- src/promptflow-devkit/promptflow/_proxy/_base_inspector_proxy.py
- src/promptflow-devkit/promptflow/_proxy/_csharp_inspector_proxy.py
- src/promptflow-devkit/promptflow/_proxy/_python_inspector_proxy.py
- src/promptflow-recording/recordings/azure/test_flow_operations_TestFlow_test_create_flow.yaml
- src/promptflow-recording/recordings/azure/test_flow_operations_TestFlow_test_get_flow.yaml
- src/promptflow-recording/recordings/azure/test_flow_operations_TestFlow_test_update_flow.yaml
- src/promptflow-recording/recordings/azure/test_run_operations_TestFlowRun_test_run_bulk_with_remote_flow.yaml
- src/promptflow-recording/recordings/azure/test_run_operations_TestFlowRun_test_run_without_generate_tools_json.yaml
customer should be able to submit a pfazure dag flow even if they don't have a local runtime with all requirements installed.
> fix: avoid generating flow.tools.json for python dag flow on pfazure run create

- src/promptflow/tests/executor/unittests/executor/_service/utils/test_process_utils.py
fix test test_invoke_sync_function_in_process_set_env
> [Internal] Fix ci test test_invoke_sync_function_in_process_set_env

- src/promptflow-devkit/promptflow/_sdk/operations/_local_azure_connection_operations.py
- src/promptflow-devkit/tests/sdk_cli_global_config_test/e2etests/test_global_config.py
> [PICKME] Fix prompty with workspace connection

- src/promptflow-azure/tests/sdk_cli_azure_test/e2etests/test_run_upload.py
- src/promptflow-devkit/promptflow/_sdk/_constants.py
- src/promptflow-devkit/promptflow/_sdk/entities/_run.py
> [SDK/CLI] Write instance_results.jsonl path in run properties

- .cspell.json
- src/promptflow-core/promptflow/_utils/flow_utils.py
- src/promptflow-core/promptflow/_utils/utils.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_flow_run.py
Fix a bug that !!omap tag will generated at the beginning of `flow.flex.yaml` in snapshot and break local to cloud
> hotfix: extra string at the beginning of yaml in snapshot

- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_csharp_sdk.py
- src/promptflow/tests/executor/unittests/batch/test_csharp_executor_proxy.py
fix 2 test on Windows:
promptflow-devkit/tests/sdk_cli_test/e2etests/test_csharp_sdk.py
- test_destroy_with_terminates_gracefully
- test_destroy_with_force_kill
> fix: csharp executor proxy ci failure

- src/promptflow-core/promptflow/_utils/tool_utils.py
- src/promptflow/tests/executor/unittests/_core/test_tools_manager.py
Currently this test will fail in python version >= 3.11, the reason is because: 
So the error message in python version >= 3.11 will be:
'Unable to retrieve tool func result due to \'ToolFuncCallScenario **ToolFuncCallScenario.REVERSE_GENERATED_BY** response must be a dict. {"index_type": "Azure Cognitive Search", "index": "index_1"} is not a dict.\'. \nPlease contact the tool author/support team for troubleshooting assistance.'
But in the python version < 3.11, the error message will be:
'Unable to retrieve tool func result due to \'ToolFuncCallScenario **reverse_generated_by** response must be a dict. {"index_type": "Azure Cognitive Search", "index": "index_1"} is not a dict.\'. \nPlease contact the tool author/support team for troubleshooting assistance.'
In order to keep the test …
> Fix test_retrieve_tool_func_result_error failure in python version >= 3.11

- docs/how-to-guides/develop-a-prompty/index.md
- docs/how-to-guides/develop-a-prompty/prompty-output-format.md
> [Doc] Change to env reference in prompty doc

- src/promptflow-core/promptflow/_utils/flow_utils.py
- src/promptflow-devkit/promptflow/_cli/_pf/_flow.py
- src/promptflow-devkit/promptflow/_internal/__init__.py
- src/promptflow-devkit/promptflow/_sdk/_utils/chat_utils.py
- src/promptflow-devkit/promptflow/_sdk/_utils/general_utils.py
- src/promptflow-devkit/promptflow/_sdk/_utils/serve_utils.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_csharp_cli.py
- src/promptflow-devkit/tests/sdk_cli_test/unittests/test_flow_serve.py
Allow run `pf flow serve` on below csharp scenario 
1. flex flow, including class init
2. use yaml as source
Add an util function to infer language of a flow
> feat: support flow.flex.yaml for csharp serve

- src/promptflow-devkit/promptflow/_sdk/_configuration.py
It's better to use local import in conf file.
> [trace][bugfix] Use local import to avoid circular import in config and trace

- src/promptflow-azure/tests/sdk_cli_azure_test/conftest.py
In Azure test, we don't need to setup local trace, so add an environ to skip.
> [fundamental] Skip local trace setup in Azure test

- src/promptflow-core/promptflow/core/_flow.py
Add `@trace` for `Prompty.__call__`, so that each prompty function can be one trace.
> [trace][bugfix] Add `@trace` for prompty `__call__`

- src/promptflow-azure/tests/sdk_cli_azure_test/e2etests/test_pfs_azure.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_trace.py
- src/promptflow-devkit/tests/sdk_pfs_test/e2etests/test_cli.py
- src/promptflow/tests/executor/e2etests/test_executor_execution_failures.py
- src/promptflow/tests/executor/unittests/_core/test_token_provider.py
- src/promptflow/tests/executor/unittests/_utils/test_tool_utils.py
Fix below tests:
+ test_validate_tool_func_result
+ str(enum) is not equal to enum.value now
+ test_get_token_with_sovereign_credential
+ multiple `with` is not supported in python 3.8 
+ test_search_line_runs_with_tokens
+ Python 3.9+ is required on Windows to support json_extract
+ test_get_connection_by_provider
+ meet error if using relative path to cwd for PFSOperation import (and actually this is not recommended)
+ test_executor_exec_node_fail
+ Python 3.11 have an extra line of stack trace
+ test_executor_exec_line_fail
+ Python 3.11 have an extra line of stack trace
> fix: test matrix 0426

- .cspell.json
- .github/workflows/promptflow-import-linter.yml
- scripts/import_linter/import_linter.py
Import linter cannot find items other than static imports.
We can add some more import statement in poetry and find circular import dynamically.
Automatic imports:
Since we have different processes, just dynamic import the module in different process is OK.
> [Import-linter] Find more import errors in import linter pipeline.

- src/promptflow-core/promptflow/executor/flow_executor.py
- src/promptflow-tracing/promptflow/tracing/_trace.py
- src/promptflow-tracing/tests/unittests/test_trace.py
For async script, system will raise asyncio.CancelledError.
We need to catch it and mark span as cancelled like KeyboardInterrupt.
(For async flow, we register signal and raise KeyboardInterrupt)
> Catch asyncio.CancelledError for cancelling async function.

- src/promptflow-core/promptflow/_core/run_tracker.py
- src/promptflow-core/promptflow/_utils/async_utils.py
- src/promptflow-core/promptflow/_utils/run_tracker_utils.py
- src/promptflow-core/promptflow/executor/flow_executor.py
Refine exec_line logic to support async generator in flow test.
This pull request primarily focuses on improving the handling of generators and asynchronous generators in the `promptflow` package. The changes ensure that the code can handle both synchronous and asynchronous generators, improve the handling of generator outputs, and refactor the way nodes are executed in the flow. 
Here are the key changes:
Improved handling of generators and asynchronous generators:
* [`src/promptflow-core/promptflow/_core/run_tracker.py`](diffhunk://#diff-a5027d19a24cb28a68ead16dfe6c54492c78d6e0e7640e80533928808cdb3422R6-L9): The `inspect` module was imported to replace the use of `GeneratorType` for checking if a value is a generator. The method `update_and_persist_generator_node_runs` was introduced to …
> [Executor] Refine executor logic to support async generator in flow test

- src/promptflow-core/promptflow/executor/_prompty_executor.py
- src/promptflow-core/promptflow/executor/_script_executor.py
- src/promptflow-core/promptflow/executor/flow_executor.py
- src/promptflow-tracing/promptflow/tracing/_operation_context.py
Add execution target to distinguish dag or non dag execution.
Will set different value for each executor
FlowExecutor: dag
ScriptExecutor: flex
PromptyExecutor: prompty
For now, when customer run `pf flow test` command to a python file, we will create flow.flex.yaml file for customer, and will report it as flex
Execution target filed will be used in
1. PowerBI AOAI token page
2. Trace telemetry
> Add execution target to distinguish dag or non-dag flow

- examples/flows/evaluation/eval-chat-math/flow.dag.yaml
Add environment into flow.dag.yaml for eval-chat-math flow:
run link in portal: https://ml.azure.com/prompts/bulkrun/eval_chat_math_variant_0_20240430_143934_923359/details?wsid=/subscriptions/96aede12-2f73-41cb-b983-6d11a904839b/resourcegroups/promptflow/providers/Microsoft.MachineLearningServices/workspaces/promptflow-eastus-dev&tid=72f988bf-86f1-41af-91ab-2d7cd011db47
> Add environment into flow.dag.yaml for eval-chat-math flow

- src/promptflow-devkit/promptflow/_sdk/_tracing.py
Currently, the cloud trace in runtime is in sync mode. This seems unnecessary. The local and runtime should use the same async pattern.
> [Internal] Make runtime cloud trace also async

- src/promptflow-devkit/promptflow/_sdk/entities/_trace.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_trace.py
For traces whose inputs and output locate in span attributes, we should support extract them for line run entity, as it's still OpenTelemetry specification. Also, this PR targets to support those non-JSON string inputs/output (user generates span with `span.set_attributes("inputs", str(dict(x=1)))`)
> [devkit][trace] Handle inputs/output in span attributes & non-JSON string inputs/output

- scripts/docs/conf.py
- src/promptflow-devkit/promptflow/_sdk/_orchestrator/experiment_orchestrator.py
- src/promptflow-devkit/promptflow/_sdk/operations/_experiment_operations.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_experiment.py
Only flow test with experiment can pass env var in.
> [Internal] Remove env var param from experiment api

- .github/workflows/build_doc_ci.yml
- .github/workflows/publish_doc.yml
- README.md
- src/promptflow/README.md
This pull request includes a minor change to the `README.md` file. The change removes the specific Python version recommendation, indicating that any Python environment is now acceptable.
> [Doc] Remove python version to avoid confusion

- .github/workflows/build_msi_installer.yml
https://github.com/microsoft/promptflow/actions/runs/9028720944/job/24811913622
> Update msi release workflow because disable storage account key access

- .github/workflows/tools_tests.yml
Add environment for build job so that we can only use one federated credential for below scenarios:
1. Manually trigger use any branch, test link https://github.com/microsoft/promptflow/actions/runs/9029698172:
2. Trigger from a PR
For all these scenarios, the subject claim will be repo:microsoft/promptflow:environment:Testing. So only need to keep below federated credential:
> Add environment for build job so that we can only use one federated credential 

- src/promptflow-devkit/promptflow/_dependencies/_pf_evals.py
- src/promptflow-devkit/promptflow/_sdk/_utilities/general_utils.py
- src/promptflow-devkit/tests/unittests/_sdk/_utilities/test_pf_eval_dependencies.py
```python
pf = PFCLient(config = {"trace.destination": 'azureml://subscriptions/......'}) # override 
pf = PFClient()        # global
pf.run(...) # will pick up config in PFClient
from promptflow._dependencies._pf_evals import get_trace_destination
url = get_trace_destination(pf) 
```
> [Internal] add public function get_trace_destination

- src/promptflow-azure/CHANGELOG.md
- src/promptflow-azure/promptflow/azure/operations/_arm_connection_operations.py
- src/promptflow-core/promptflow/core/_connection.py
- src/promptflow-devkit/CHANGELOG.md
- src/promptflow-devkit/promptflow/_cli/_pf/_connection.py
- src/promptflow-devkit/promptflow/_sdk/entities/_connection.py
- src/promptflow-devkit/promptflow/_sdk/operations/_connection_operations.py
- src/promptflow-devkit/promptflow/_sdk/operations/_local_azure_connection_operations.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_connection.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_custom_strong_type_connection.py
- src/promptflow-devkit/tests/sdk_cli_test/unittests/test_connection.py
- src/promptflow/CHANGELOG.md
- Return the secrets in the connection object by default to improve flex flow experience.
- Behaviors not changed: 'pfazure connection'/'pf connection' command will scrub secrets.
- New behavior: connection object by `client.connection.get` will have real secrets. `print(connection_obj)` directly will scrub those secrets. `print(connection_obj.api_key)` or `print(connection_obj.secrets)` will print the REAL secrets.
- Workspace listsecrets permission is required to get the Azure AI connection secrets. Call `client.connection.get(name, with_secrets=True)` if you want to get without the secrets and listsecrets permission.
> [Connection] Return secrets in connection obj for better flex flow experience

- src/promptflow-core/promptflow/executor/_prompty_executor.py
- src/promptflow-core/promptflow/executor/_service/apis/batch.py
- src/promptflow-core/promptflow/executor/_service/utils/batch_coordinator.py
- src/promptflow-core/promptflow/executor/flow_executor.py
- src/promptflow/tests/executor/unittests/executor/_service/apis/test_batch.py
- src/promptflow/tests/executor/utils.py
Return inputs definition and has aggregation by initialize api in execution server to avoid creating flow executor in runtime container.
> [Internal][Executor] Return inputs definition and has aggregation by initialize api in execution server

- src/promptflow-devkit/promptflow/_sdk/operations/_local_storage_operations.py
promptflow logs are lost after the log line `[promptflow._sdk._orchestrator.run_submitter][INFO] - Submitting run xxx`, this change gets back those logs, and make sure content in `logs.txt` remain unchanged.
> [SDK/CLI] Fix log level setting for promptflow logger

- src/promptflow-core/promptflow/_utils/async_utils.py
- src/promptflow-core/promptflow/executor/flow_executor.py
Quick fix for the issue #3069
This pull request primarily focuses on changes to the `promptflow-core` package to improve handling of synchronous and asynchronous iterators. The most significant changes include the creation of a new function `sync_iterator_to_async` in `async_utils.py` and its subsequent integration into the `flow_executor.py` module. 
Here are the key changes, grouped by theme:
**Addition of new utility function:**
* [`src/promptflow-core/promptflow/_utils/async_utils.py`](diffhunk://#diff-ebca5e7d6a45f737be917f296f2fb0a3480fa26bc378bde80f11368c9ac2c4fbR113-R124): A new function `sync_iterator_to_async` has been added. This function converts a synchronous iterator to an asynchronous one using a thread pool executor.
**Changes to the `flow_executor.py` module:**
* …
> [Executor] Convert sync generator to async generator

- src/promptflow-core/promptflow/executor/_async_nodes_scheduler.py
- src/promptflow-core/promptflow/executor/flow_executor.py
Improve the timeout handling of async scheduler.
Before:
The async nodes would be keep running until the process is killed.
After:
The async function would got an asyncio.CanceledError, then the line raises LineExecutionTimeoutError.
This pull request introduces changes in the `src/promptflow-core/promptflow/executor/_async_nodes_scheduler.py` and `src/promptflow-core/promptflow/executor/flow_executor.py` files to handle line execution timeouts. The `Optional` type has been imported and a `timeout_seconds` parameter has been added to the `execute` and `_execute_with_thread_pool` methods. A timeout mechanism has been implemented in `_execute_with_thread_pool` to cancel tasks that exceed the specified timeout. A `cancel_tasks` method has also been added to cancel tasks and yield control to …
> [Executor] Add timeout task to async scheduler to achieve timeout feature.

- src/promptflow-core/promptflow/_utils/flow_utils.py
- src/promptflow-core/promptflow/core/_serving/app_base.py
- src/promptflow-devkit/promptflow/_sdk/_utilities/general_utils.py
- src/promptflow-devkit/promptflow/_sdk/_utilities/serve_utils.py
- src/promptflow-devkit/tests/sdk_cli_test/conftest.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_flow_serve.py
- src/promptflow-devkit/tests/sdk_cli_test/unittests/test_flow_serve_cli.py
- src/promptflow-devkit/tests/sdk_cli_test/unittests/test_utils.py
- src/promptflow/tests/test_configs/prompty/single_prompty/prompty_example.prompty
Support passing a directory without `flow.dag.yaml` nor `flow.flex.yaml` but with 1 and only 1 prompty in it as `source` in `pf flow serve`.
App support is already done by support prompty in `init_executable`, so this PR is mainly focus on changes in cli.
Note that this is not a full support for prompty in `pf flow serve` as there can usually be multiple prompty in 1 directory. We will need to figure out this in next release.
> feat: pf flow serve support for directory with 1 and only 1 prompty

- src/promptflow-devkit/promptflow/_sdk/_orchestrator/run_submitter.py
- src/promptflow-devkit/promptflow/_sdk/operations/_run_operations.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_flow_run.py
**Portal url related**
If `portal_url` is `None`, no need to update run; otherwise, a SQL error will be raised, error message looks like: `"SQL: UPDATE run_info SET  WHERE run_info.name = ?"`
**Flow type**
`Run._flow_type` returns wrong flow type for flex flow run without YAML in flow directory, as a workaround, create a new exclusive function to get that for `pf run visualize`.
> [devkit] Fix potential empty portal url & wrong flow type of run

- src/promptflow-core/promptflow/_core/token_provider.py
Fixes #3243
PromptFlow currently falls back to using DefaultAzureCredential and fetching a token for the Oauth 1.0 audience. That is not compatible with all credentials in the chain, specifically, the AzureDeveloperCliCredential which is Oauth 2.0 only. This PR changes the audience value to the correct scope value, and renames variables accordingly.
I tested with the AzureDeveloperCliCredential and AzureCliCredential flow.
> Update token_provider.py to Oauth2.0 scope instead of OAuth 1.0 audience

- src/promptflow-devkit/promptflow/_sdk/_tracing.py
- src/promptflow-tracing/promptflow/tracing/_start_trace.py
`OTEL_EXPORTER_OTLP_ENDPOINT` stands for the collector supports both traces and metrics; prompt flow currently only supports traces collection, so it's more properly to use `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`.
However, to prevent breaking change in runtime, for consumer, still check two environs.
> [tracing][devkit] Use `OTEL_EXPORTER_OTLP_TRACES_ENDPOINT` for OTLP endpoint environ

- src/promptflow-core/promptflow/executor/_script_executor.py
- src/promptflow-core/tests/core/e2etests/test_eager_flow.py
> [Executor] Update script executor to support async generator in batch run

- src/promptflow-devkit/promptflow/_sdk/_tracing.py
New SDK will set different environ (`OTEL_EXPORTER_OTLP_TRACES_ENDPOINT`), as consumer, need to check both to avoid breaking change.
> [trace][bugfix] Check both OTel environ for exporter to PFS

- src/promptflow-core/promptflow/core/_model_configuration.py
- src/promptflow-core/tests/core/e2etests/test_eager_flow.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_flow_test.py
- src/promptflow-devkit/tests/sdk_cli_test/unittests/test_prompty.py
Reverts microsoft/promptflow#3261
When create aoai or openai clinet, api_key, api_version and base_url will be get from env if not set.
> Revert "[Prompty] Check the required parameters in model configuration is configured"

- src/promptflow-azure/promptflow/azure/operations/_async_run_uploader.py
- src/promptflow-azure/promptflow/azure/operations/_run_operations.py
- src/promptflow-azure/tests/sdk_cli_azure_test/e2etests/test_run_upload.py
- src/promptflow-azure/tests/sdk_cli_azure_test/e2etests/test_telemetry.py
- src/promptflow-azure/tests/sdk_cli_azure_test/unittests/test_run_operations.py
- src/promptflow-devkit/promptflow/_sdk/_configuration.py
- src/promptflow-devkit/promptflow/_sdk/_orchestrator/run_submitter.py
- src/promptflow-evals/promptflow/evals/evaluate/_utils.py
Put this uploader initialization part to be executed simutaneously with run execution, therefore reduce 10-17 seconds.
> [SDK/CLI][Perf] Initialize run uploader simultaneously with run execution

- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_flow_serve.py
Fix test nit, there is no public is_live method provided.
> [Test Fix]Fix test nit, there is no public is_live method provided.

- src/promptflow-evals/promptflow/evals/evaluate/_evaluate.py
> [pf-evals] Fix the user agent not populated

- src/promptflow-tools/promptflow/tools/aoai.py
- src/promptflow-tools/promptflow/tools/openai.py
only pass user parameter when it is not empty for chat api
Test against below package:
--extra-index-url https://azuremlsdktestpypi.azureedge.net/test-promptflow/
promptflow_tools==0.0.430
> only pass user parameter when it is not empty for chat api

- src/promptflow-evals/promptflow/evals/evaluate/_code_client/code_client.py
- src/promptflow-evals/promptflow/evals/evaluate/_evaluate.py
- src/promptflow-evals/tests/evals/e2etests/test_evaluate.py
Handle the numeric columns in the evaluator output. See work item 3216567
> Handle numeric columns

- src/promptflow-devkit/promptflow/_sdk/_utilities/tracing_utils.py
Ignore aggregate node for trace telemetry.
For aggregate node trace, it doesn't have parent span, line run id or batch run id.
So, will be wrongly marked as script execution.
> Ignore aggregation node for trace telemetry.

- src/promptflow-devkit/CHANGELOG.md
- src/promptflow-devkit/promptflow/_sdk/_service/apis/collector.py
- src/promptflow-devkit/promptflow/_sdk/_service/utils/utils.py
- src/promptflow-devkit/promptflow/_sdk/_utilities/tracing_utils.py
- src/promptflow-recording/promptflow/recording/azure/bases.py
- src/promptflow/CHANGELOG.md
This PR targets to add trace usage telemetry in custom dimensions, which looks like below:
There will be a thread scheduled to flush trace telemetry in memory - different process worker stores telemetry in different process, so it's difficult to flush for each, so a scheduled thread shall work best in this case.
Besides, fixes a replay test introduced in #3348 , which changes test class init signature, and leads to our replay tests breaking.
> [trace][feature] Add trace usage telemetry

- src/promptflow-azure/tests/sdk_cli_azure_test/e2etests/test_run_upload.py
- src/promptflow-devkit/promptflow/_sdk/_orchestrator/run_submitter.py
- src/promptflow-devkit/promptflow/_sdk/entities/_run.py
Local to cloud tracking has incorrect creation time as shown in screenshot below. This PR fixes this issue.
> Fixing timezone issue with local to cloud run

- .github/workflows/sdk-cli-azure-test-production.yml
- .github/workflows/sdk-cli-azure-test-pull-request.yml
- src/promptflow-azure/tests/conftest.py
- src/promptflow-recording/promptflow/recording/azure/constants.py
- src/promptflow-recording/promptflow/recording/azure/utils.py
#3390 introduces some sanitizations, which breaks `promptflow-azure` replay test. This PR targets to add an environment variable to distinguish `promptflow-azure` and `promptflow-evals`.
Besides, make `promptflow-azure` replay test listen on pf-recording code path to avoid such breaking.
> [azure][bugfix] Fix Azure replay test wrong sanitizations

- src/promptflow-devkit/CHANGELOG.md
- src/promptflow-devkit/promptflow/_sdk/_tracing.py
- src/promptflow-devkit/tests/sdk_cli_test/unittests/test_trace.py
- src/promptflow/CHANGELOG.md
In some cases (we have observed in runtime scenario, related to mlflow), tracer provider can be set as `trace.NoOpTracerProvider`, which does not have method `add_span_processor` and lead to error. This PR adds a check on that to avoid such crash.
> [devkit][bugfix] Add check for `trace.NoOpTracerProvider` to avoid crash

- src/promptflow-tools/tests/test_acs.py
Failed tool ci: https://github.com/microsoft/promptflow/actions/runs/9542727564/job/26298045963
```
FAILED src/promptflow-tools/tests/test_acs.py::TestAzureContentSafety::test_azure_content_safety_analyze_happy_path - promptflow.tools.exception.AzureContentSafetySystemError: Error in detecting content: Key based authentication is disabled for this resource.
```
> [Internal] Fix tool ci by skipping acs test since the test resource is not valid

- .github/workflows/build_doc_ci.yml
- .github/workflows/promptflow-executor-e2e-test.yml
- .github/workflows/promptflow-executor-unit-test.yml
- .github/workflows/promptflow-import-linter.yml
Pin `tenacity` to avoid issue described in https://github.com/langchain-ai/langchain/issues/22972.
> [fundamental][bugfix] Pin `tenacity`<8.4.0 to fix import-linter CI

- src/promptflow-evals/promptflow/evals/evaluate/_evaluate.py
- src/promptflow-evals/promptflow/evals/evaluate/_telemetry/__init__.py
- src/promptflow-evals/promptflow/evals/evaluate/_utils.py
- src/promptflow-evals/tests/evals/unittests/test_evaluate_telemetry.py
- src/promptflow-evals/tests/evals/unittests/test_evaluators/apology_dag/apology.py
- src/promptflow-evals/tests/evals/unittests/test_evaluators/apology_dag/flow.dag.yaml
- src/promptflow-evals/tests/evals/unittests/test_evaluators/apology_prompty/apology.prompty
- src/promptflow-evals/tests/evals/unittests/test_evaluators/apology_prompty/sample.json
> Adding telemetry for evaluate API

- docs/cloud/azureai/use-flow-in-azure-ml-pipeline.md
- examples/tutorials/run-flow-with-pipeline/pipeline.ipynb
`pf flow validate` don't have `file` option. The correct option is `source` , right?
```bash
% pf flow validate -h
usage: pf flow validate [-h] --source SOURCE [--verbose] [-d]
Validate a flow and generate flow.tools.json for the flow.
options:
-h, --help       show this help message and exit
--source SOURCE  The flow or run source to be used.
--verbose        Increase logging verbosity. Use --debug for full debug logs.
-d, --debug      The flag to turn on debug mode for cli.
Examples:
pf flow validate --source <path_to_flow>
```
> [docs]fix invalid option of `pf flow validate`

- .github/pipelines/compliance_check.yml
CI "Compliance Check" starts to fail recently (one example: #3478 ); the root cause is that the PoliCheck does not support fork repository, so the step that generates result tsv will be skipped, resulting in the following step that will consume the tsv file break.
This PR targets to fix this issue by checking the tsv file first, and create an empty one if the file does not exist; then the following step will regard everything is fine and goes on as before.
> [fundamental] Touch result file for fork repository

- src/promptflow-evals/promptflow/evals/evaluate/_eval_run.py
> Using token Cache to reduce token get calls

- README.md
- docs/index.md
- scripts/docs/_static/custom.css
- scripts/docs/conf.py
- src/promptflow/README.md
[doc] highlight tracing feature
> [doc] highlight tracing feature

- src/promptflow-evals/promptflow/evals/evaluate/_eval_run.py
- src/promptflow-evals/promptflow/evals/evaluate/_utils.py
- src/promptflow-evals/tests/evals/e2etests/test_metrics_upload.py
- src/promptflow-evals/tests/evals/unittests/test_eval_run.py
In this PR we are doing three things:
1. Making evaluator run a context manager
2. Moving function, writing properties to the run history to the evaluation run as a method
3. Removing code to keep evaluator run as a singletone as we, generally, do not need it.
4. Doing some unittest refactoring and adding/removing appropriate tests.
See work item 3334452.
> Make evaluation run a context manager instead of a singleton.

- src/promptflow-evals/promptflow/evals/evaluators/_coherence/_coherence.py
- src/promptflow-evals/promptflow/evals/evaluators/_fluency/_fluency.py
- src/promptflow-evals/promptflow/evals/evaluators/_groundedness/_groundedness.py
- src/promptflow-evals/promptflow/evals/evaluators/_relevance/_relevance.py
- src/promptflow-evals/promptflow/evals/evaluators/_similarity/_similarity.py
- src/promptflow-tracing/promptflow/tracing/_integrations/_openai_injector.py
- src/promptflow-tracing/tests/unittests/test_openai_injector.py
Appending header values if clashing headers found between injected headers and original headers in request.
> Fixing user agent header name

- src/promptflow-tracing/tests/e2etests/simple_functions.py
- src/promptflow-tracing/tests/e2etests/test_tracing.py
This pull request addresses the issue of the skipped test case due to the retirement of the `text-ada-001` model after June 14. The following changes have been made to ensure the test case works correctly:
- Removed the skip mark from the test case.
- Replaced the `text-ada-001` model with the `gpt-35-turbo-instruct` model to make the AOAI endpoint functional for the test case.
> Fix Test Case by Replacing `text-ada-001` with `gpt-35-turbo-instruct`

- src/promptflow-azure/pyproject.toml
`azure-ai-ml` breaks Azure replay test since version 1.19.0, this PR targets to pin the version as a short-term workaround.
> [azure][test] pin `azure-ai-ml` to aovid azure replay test breaking

- examples/requirements.txt
- src/promptflow-azure/CHANGELOG.md
- src/promptflow-azure/pyproject.toml
- src/promptflow-core/CHANGELOG.md
- src/promptflow-core/pyproject.toml
- src/promptflow-devkit/CHANGELOG.md
- src/promptflow-devkit/pyproject.toml
- src/promptflow-tracing/pyproject.toml
- src/promptflow/CHANGELOG.md
- src/promptflow/promptflow/_version.py
> [promptflow][release] 1.15.0 release branch merge back

- src/promptflow-core/promptflow/_utils/logger_utils.py
1. LoggerHandler will control the final output log so we set the logger.level to debug to collect all logs previously
2. The reason to change this is promptflow serving will choose whether to disable logs based on logger.level. 
https://github.com/microsoft/promptflow/blob/main/src/promptflow-core/promptflow/core/_serving/flow_invoker.py#L191
> Set logger level instead of using debug

- src/promptflow-devkit/promptflow/_sdk/_orchestrator/experiment_orchestrator.py
- src/promptflow-devkit/tests/sdk_cli_test/e2etests/test_experiment.py
Added command parameter detection before executing commands to avoid risky characters.
> [experiment] Verify command injection when starting experiments asynchronously

- src/promptflow-evals/CHANGELOG.md
- src/promptflow-evals/promptflow/evals/synthetic/adversarial_simulator.py
- src/promptflow-evals/promptflow/evals/synthetic/jailbreak_adversarial_simulator.py
- src/promptflow-evals/tests/evals/e2etests/test_adv_simulator.py
Add randomization to Adversarial Simulator via 2 new keyword arguments. Enabled by default. The Jailbreak sim internally selects a randomization seed for both its child simulators to ensure consistency.
Also added some tests for this.
> randomization

- src/promptflow-evals/promptflow/evals/_common/rai_service.py
- src/promptflow-evals/promptflow/evals/evaluators/_eci/_eci.py
- src/promptflow-evals/promptflow/evals/evaluators/_protected_materials/_protected_materials.py
- src/promptflow-evals/promptflow/evals/synthetic/adversarial_scenario.py
- src/promptflow-evals/tests/evals/e2etests/test_adv_simulator.py
- src/promptflow-evals/tests/evals/e2etests/test_builtin_evaluators.py
A collection of small changes to the ECI and IP evaluators to match the spec more closely. Changes include:
- refactor non-content safety evaluator response parsing to add metric prefix to results. This includes special logic to capitalize the 'eci' prefix.
- Changed ECI simulator enum to just be 'ECI'.
> changes to align with spec

- src/promptflow-evals/promptflow/evals/_common/rai_service.py
- src/promptflow-evals/promptflow/evals/evaluators/_eci/_eci.py
- src/promptflow-evals/tests/evals/e2etests/test_builtin_evaluators.py
- src/promptflow-evals/tests/evals/unittests/test_evaluate.py
This PR changes ECI case from upper to lower to match other evaluator type casing and integrate better with UI evaluation flows.
> Change eci prefix from upper case to lowercase

- src/promptflow-tracing/CHANGELOG.md
- src/promptflow-tracing/promptflow/tracing/_trace.py
The token calculation logic in promptflow-tracing merges two dictionaries related to token usage.
i.e. Given these two dictionaries:
```json
{ "completion_tokens": 146, "prompt_tokens": 166, "total_tokens": 312 }
```
```json
{ "completion_tokens": 10, "prompt_tokens": 10, "total_tokens": 20 }
```
The merged result will be:
```json
{ "completion_tokens": 156, "prompt_tokens": 176, "total_tokens": 332 }
```
However, for some customized models, there might be more additional fields populated in the dictionaries, like:
```json
{ "completion_tokens": 146, "prompt_tokens": 166, "total_tokens": 312, "completion_tokens_details": null }
```
Which causes the merging logic crash:
This PR is to fix the issue. It converts `null`s to `0`s to avoid Python from raising errors.
> Fix bug in token usage merging logic for promptflow-tracing SDK

- src/promptflow-devkit/CHANGELOG.md
- src/promptflow/tests/executor/e2etests/test_langchain.py
> CHANGELOG.md broken link fix 

- src/promptflow-core/promptflow/core/_prompty_utils.py
Current regex for parsing of tool_calls breaks if there is an array in the arguments (as it has a ']').
Consume up to end of block so it only matches the closing ']' and not any intermediate ones.
> prompty: fix parsing of tool_calls when array in arguments

- src/promptflow-tracing/CHANGELOG.md
- src/promptflow-tracing/promptflow/tracing/_trace.py
In the latest version of OpenAI some keys have tokens that are not ints. This is causing TypeErrors like 
`TypeError: unsupported operand type(s) for +: 'int' and 'dict'`
This aims to handle None types and Dicts better in tracing.
Should resolve bug #3834
> Fixed TypeError in Tracing issue with tokens that are dicts

- src/promptflow-tracing/CHANGELOG.md
- src/promptflow/CHANGELOG.md
> Changelog update for release 1.1.7.0

- .github/workflows/promptflow-import-linter.yml
This pull request fixes an issue with the import lint PR workflow, which errors out with message: 
```
Poetry could not find a pyproject.toml file in /home/runner/work/promptflow/promptflow or its parents
```
> fix(ci): Fix "poetry could not find a pyproject.toml" in import lint workflow

- src/promptflow-core/promptflow/_utils/connection_utils.py
- src/promptflow-core/promptflow/core/_serving/v1/blueprint/static_web_blueprint.py
- src/promptflow-core/promptflow/core/_utils.py
- src/promptflow-devkit/promptflow/_cli/_pf/_init_entry_generators.py
> Use SandboxedEnvironment for Template
